### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>auto-instrumentations-node: 0.30.0</summary>

### Features

* **instrumentation-redis:** add support for redis@^4.0.0 ([#982](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/982)) ([1da0216](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/1da0216180de694c15ec356d476f465811757ae4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-redis bumped from ^0.30.0 to ^0.31.0
    * @opentelemetry/instrumentation-redis-4 bumped from ^0.29.0 to ^0.30.0
</details>

<details><summary>instrumentation-redis: 0.31.0</summary>

### Features

* **instrumentation-redis:** add support for redis@^4.0.0 ([#982](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/982)) ([1da0216](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/1da0216180de694c15ec356d476f465811757ae4))
</details>

<details><summary>instrumentation-redis-4: 0.30.0</summary>

### Features

* **instrumentation-redis:** add support for redis@^4.0.0 ([#982](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/982)) ([1da0216](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/1da0216180de694c15ec356d476f465811757ae4))
* upstream mocha instrumentation testing plugin from ext-js [#621](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/621) ([#669](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/669)) ([a5170c4](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a5170c494706a2bec3ba51e59966d0ca8a41d00e))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by Flarna** [comment]
I think we should convince release please somehow to release all packages.

**Comment by AWare** [comment]
@Flarna that would be very much appreciated.

**Comment by dyladan** [comment]
Are there unreleased packages you're waiting on?

**Comment by dyladan** [comment]
DO NOT MERGE UNTIL #1040 IS MERGED

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-v0.31.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-4-v0.30.0 :sunflower:

**Comment by dyladan** [comment]
Release please has had some unfortunate problems and growing pains. Would be nice to have some more manual control when things go wrong.

**Pull request merged**
