### PR TITLE
feat: create an instrumentation package for ogma

### PR DESCRIPTION
**Pull request by jmcdo29**
## Which problem is this PR solving?

- Providing Instrumentation support for the [Ogma](https://ogma.jaymcdoniel.dev) logger

## Short description of the changes

- I'm the author of the Ogma logger and wanted to provide instrumentation support for it, as I've had requests for such in the past. I took a similar approach as the `pino` instrumentation implementation, and modified it for how Ogma works. All tests should be passing, and I've assigned myself as the codeowner for this instrumentation. If there's anything else I need to do, please let me know, I'll be more than happy to do so

### CODE REVIEW

**Comment by jmcdo29** [comment]
Would I be able to request a review for this? Please and thank you

**Comment by jmcdo29** [comment]
I'm doing what I can top keep this PR active and current so it can be reviewed and merged when ready. Let me know if there's anything else that can be done here :smile:

**Comment by SocketSomeone** [comment]
Any updates?

**Comment by pichlermarc** [comment]
> I'm the author of the Ogma logger and wanted to provide instrumentation support for it, as I've had requests for such in the past. I took a similar approach as the `pino` instrumentation implementation, and modified it for how Ogma works. All tests should be passing, and I've assigned myself as the codeowner for this instrumentation. If there's anything else I need to do, please let me know, I'll be more than happy to do so

Hi @jmcdo29 usually there's an instrumentation request issue that should preceed a pull request adding a new instrumentation. 

Is there a reason why you decided to add this instrumentation here as opposed to hosting it in a separate repo and adding it to the [instrumentation registry](https://opentelemetry.io/ecosystem/registry/)? 

Usually we recommend that projects host their own instrumentations as it provides them with more control over the instrumentation. It also is easier for us as we're often not familiar with the library that's being instrumented.

**Comment by pichlermarc** [comment]
Adding native instrumentation might also be an option (directly depending on the `@opentelemetry/api` package and emitting telemetry this way).

**Comment by jmcdo29** [comment]
I'm not opposed to hosting it in the ogma repo at all. Thanks for getting back to me on this. It _seemed_ that adding the instrumentation to the repo was a "proper" way to go about it, but obviously any kind of hosted packages can work. I'll close this out and host it in my own repo as to not keep this open longer than it needs to be. Thanks.

**Pull request closed without merging**
