### PR TITLE
refactor(instrumentation-redis): Use exported semconv strings

### PR DESCRIPTION
**Pull request by Zirak**
## Which problem is this PR solving?

- Part of #2025

I was already in the Redis neighborhood with #2072 and thought to help out, thanks @JamieDanielson and @maryliag for prior work on this.

## Short description of the changes

For `@opentelemetry/instrumentation-redis`:
- Bump `@opentelemetry/semantic-conventions` to `^1.22.0`
- Rewire to use `SEMATTR` and `DBSYSTEMVALUES` constants
- Add docs for which attributes the instrumentation sets

### CODE REVIEW

**Comment by maryliag** [comment]
@Zirak looks like you're missing the changes on `package-lock.json`, can you run `npm install` on this package to have that file updated?

**Comment by Zirak** [comment]
Of course, silly me! Thanks for the spot.

**Review by david-luna — APPROVED** [review]
thanks for your contribution :)

**Review by JamieDanielson — APPROVED** [review]
Thanks for this!

**Review by blumamir — APPROVED** [review]

**Pull request merged**
