### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>@opentelemetry/auto-instrumentations-node: 0.36.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-amqplib bumped from ^0.32.1 to ^0.32.2
    * @opentelemetry/instrumentation-dataloader bumped from ^0.3.1 to ^0.4.0
    * @opentelemetry/instrumentation-dns bumped from ^0.31.1 to ^0.31.2
    * @opentelemetry/instrumentation-nestjs-core bumped from ^0.32.1 to ^0.32.2
</details>

<details><summary>instrumentation-amqplib: 0.32.2</summary>

### Bug Fixes

* **amqplib:** stop importing from `amqplib` directly in compiled types ([#1394](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1394)) ([9d0198c](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/9d0198ca104a34726a7b41dd910df275e0c5336d))
</details>

<details><summary>instrumentation-dataloader: 0.4.0</summary>

### Features

* **instrumentation-dataloader:** add dataloader name to span names ([#1345](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1345)) ([712b559](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/712b559416e0d86ef29ed06d46c180ef8360b411))
</details>

<details><summary>instrumentation-dns: 0.31.2</summary>

### Bug Fixes

* **instrumentation-dns:** fix instrumentation of `dns/promises` ([#1377](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1377)) ([6d08157](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/6d08157300faf418e886315384e6b705a0e13683))
</details>

<details><summary>instrumentation-nestjs-core: 0.32.2</summary>

### Bug Fixes

* **vinyl-fs:** removed unnecessary dep types/vinyl-fs ([#1390](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1390)) ([5a8df08](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/5a8df0826b24c37ae5b992d5f68286f9742ce79f))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by blumamir — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.36.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-amqplib-v0.32.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-dataloader-v0.4.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-dns-v0.31.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-nestjs-core-v0.32.2 :sunflower:

**Pull request merged**
