### PR TITLE
chore: permanently deprecate opentelemetry-browser-extension-autoinjection

### PR DESCRIPTION
**Pull request by svrnm**
As discussed in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1152#issuecomment-2173744798 this PR will permanently deprecate the OpenTelemetry Browser Extension in this repository. While this was not a lighthearted decision, I think it is the right thing to do, since it

* reduces the maintanance bruden for the JS maintainers
* allows me to focus on the areas of the OTel project that need my attention
* allows other extensions (like https://github.com/tbrockman/opentelemetry-browser-extension) to shine and take it's place

In this PR I make sure that it is clear that this is permanent, but that there are alternatives and that they can be found via the Registry (and people can add more if they want to)

@SimenB I appreciate the help you provided on fixing and debugging the underlying issue with webpack4&webpack5 and I apologize that this didn't land

Note, that I kicked off a conversation with @tbrockman about the extension at https://github.com/tbrockman/opentelemetry-browser-extension and shared some if the ideas I had for the extension. I also played around with this extension and it is much feature-richer and stable than what I created, so at the end this is a happy ending!

Thank you all

### CODE REVIEW

**Review by pichlermarc — APPROVED** [review]
Thank you for the update. 
Happy to hear that there's a third-party replacement for the package. :slightly_smiling_face:

**Comment by blumamir** [comment]
Thanks @svrnm 

@open-telemetry/android-maintainers do you think we should keep the deprecated package in this repo?

**Comment by pichlermarc** [comment]
@blumamir I think we should at keep the README.md to tell people where to go to find the replacement. :slightly_smiling_face:

**Comment by LikeTheSalad** [comment]
> Thanks @svrnm
> 
> @open-telemetry/android-maintainers do you think we should keep the deprecated package in this repo?

I'm a bit confused, is it related to an android package?

**Comment by pichlermarc** [comment]
> I'm a bit confused, is it related to an android package?

@blumamir must've pinged the wrong group. I think he meant @open-telemetry/javascript-maintainers :slightly_smiling_face:

**Comment by blumamir** [comment]
> > I'm a bit confused, is it related to an android package?
> 
> @blumamir must've pinged the wrong group. I think he meant @open-telemetry/javascript-maintainers 🙂

yes, my bad. sorry about that :)

**Comment by svrnm** [comment]
> @blumamir I think we should keep the README.md to tell people where to go to find the replacement. 🙂

I am OK with both, but I would prefer to keep it `archived` for that same reason

**Comment by JamieDanielson** [comment]
> > @blumamir I think we should keep the README.md to tell people where to go to find the replacement. 🙂
> 
> I am OK with both, but I would prefer to keep it `archived` for that same reason

I see a bit of "why not both" here. If we keep the README, we can also include a link to the code (say from a previous tag) and remove the code from main. Another alternative is to - whether now or later - create a separate markdown file linked from the main README that includes an index (list) of deprecated/archived projects like this one, i.e. `deprecated.md`

**Comment by svrnm** [comment]
> I see a bit of "why not both" here. If we keep the README, we can also include a link to the code (say from a previous tag) and remove the code from main. Another alternative is to - whether now or later - create a separate markdown file linked from the main README that includes an index (list) of deprecated/archived projects like this one, i.e. `deprecated.md`

I like that (doing it incrementally + having a deprecated.md that points to the commit with the code).

I know that JS SIG is not the only one looking into that, I wonder how other SIGs are handling that?

**Comment by blumamir** [comment]
I support removing the code (which one can also find in git by checking out to an early commit) and leaving just a note in the README to communicate the status so that it won't go away for some reasonable time.

The code pops up in IDE searches and may still promote old practices which I don't see any good reason to keep anymore.

**Comment by svrnm** [comment]
@blumamir @pichlermarc @JamieDanielson whatever you prefer doing I can implement via this PR, or feel free to go ahead and raise one separately to get this fixed

**Comment by pichlermarc** [comment]
> @blumamir @pichlermarc @JamieDanielson whatever you prefer doing I can implement via this PR, or feel free to go ahead and raise one separately to get this fixed

Thanks :+1: 
Let's merge this PR and then we can still follow up on removing the code. It being here for now does not hurt anyone :slightly_smiling_face:

**Pull request merged**
