### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>auto-instrumentations-node: 0.41.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-amqplib bumped from ^0.33.5 to ^0.34.0
    * @opentelemetry/instrumentation-aws-lambda bumped from ^0.37.4 to ^0.38.0
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.37.2 to ^0.38.0
    * @opentelemetry/instrumentation-bunyan bumped from ^0.34.1 to ^0.35.0
    * @opentelemetry/instrumentation-cassandra-driver bumped from ^0.34.2 to ^0.35.0
    * @opentelemetry/instrumentation-connect bumped from ^0.32.4 to ^0.33.0
    * @opentelemetry/instrumentation-cucumber bumped from ^0.2.1 to ^0.3.0
    * @opentelemetry/instrumentation-dataloader bumped from ^0.5.4 to ^0.6.0
    * @opentelemetry/instrumentation-dns bumped from ^0.32.5 to ^0.33.0
    * @opentelemetry/instrumentation-express bumped from ^0.34.1 to ^0.35.0
    * @opentelemetry/instrumentation-fs bumped from ^0.8.4 to ^0.9.0
    * @opentelemetry/instrumentation-fastify bumped from ^0.32.6 to ^0.33.0
    * @opentelemetry/instrumentation-generic-pool bumped from ^0.32.5 to ^0.33.0
    * @opentelemetry/instrumentation-graphql bumped from ^0.36.1 to ^0.37.0
    * @opentelemetry/instrumentation-hapi bumped from ^0.33.3 to ^0.34.0
    * @opentelemetry/instrumentation-ioredis bumped from ^0.36.1 to ^0.37.0
    * @opentelemetry/instrumentation-knex bumped from ^0.32.4 to ^0.33.0
    * @opentelemetry/instrumentation-koa bumped from ^0.36.4 to ^0.37.0
    * @opentelemetry/instrumentation-lru-memoizer bumped from ^0.33.5 to ^0.34.0
    * @opentelemetry/instrumentation-memcached bumped from ^0.32.5 to ^0.33.0
    * @opentelemetry/instrumentation-mongodb bumped from ^0.38.1 to ^0.39.0
    * @opentelemetry/instrumentation-mongoose bumped from ^0.34.0 to ^0.35.0
    * @opentelemetry/instrumentation-mysql bumped from ^0.34.5 to ^0.35.0
    * @opentelemetry/instrumentation-mysql2 bumped from ^0.34.5 to ^0.35.0
    * @opentelemetry/instrumentation-nestjs-core bumped from ^0.33.4 to ^0.34.0
    * @opentelemetry/instrumentation-net bumped from ^0.32.5 to ^0.33.0
    * @opentelemetry/instrumentation-pg bumped from ^0.37.2 to ^0.38.0
    * @opentelemetry/instrumentation-pino bumped from ^0.34.5 to ^0.35.0
    * @opentelemetry/instrumentation-redis bumped from ^0.35.5 to ^0.36.0
    * @opentelemetry/instrumentation-redis-4 bumped from ^0.35.6 to ^0.36.0
    * @opentelemetry/instrumentation-restify bumped from ^0.34.3 to ^0.35.0
    * @opentelemetry/instrumentation-router bumped from ^0.33.4 to ^0.34.0
    * @opentelemetry/instrumentation-socket.io bumped from ^0.35.0 to ^0.36.0
    * @opentelemetry/instrumentation-tedious bumped from ^0.6.5 to ^0.7.0
    * @opentelemetry/instrumentation-winston bumped from ^0.33.1 to ^0.34.0
    * @opentelemetry/resource-detector-alibaba-cloud bumped from ^0.28.5 to ^0.28.6
    * @opentelemetry/resource-detector-aws bumped from ^1.3.5 to ^1.3.6
    * @opentelemetry/resource-detector-container bumped from ^0.3.5 to ^0.3.6
    * @opentelemetry/resource-detector-gcp bumped from ^0.29.5 to ^0.29.6
</details>

<details><summary>auto-instrumentations-web: 0.36.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-document-load bumped from ^0.34.1 to ^0.35.0
    * @opentelemetry/instrumentation-user-interaction bumped from ^0.34.1 to ^0.35.0
</details>

<details><summary>contrib-test-utils: 0.36.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>host-metrics: 0.35.0</summary>

### ⚠ BREAKING CHANGES

* **host-metrics:** fix process.cpu.* metrics ([#1785](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1785))

### Bug Fixes

* **host-metrics:** fix process.cpu.* metrics ([#1785](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1785)) ([1e90a40](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/1e90a4055144e48ec007b6237b6a4fecba2748fb))
</details>

<details><summary>instrumentation-amqplib: 0.34.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-aws-lambda: 0.38.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-aws-sdk: 0.38.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Bug Fixes

* **instrumentation-aws-sdk:** make empty context when SQS message has no propagation fields ([#1889](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1889)) ([577a291](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/577a291cd527606b331d6732ba0eccc75422a0fc))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/propagation-utils bumped from ^0.30.5 to ^0.30.6
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-bunyan: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-cassandra-driver: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-connect: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-cucumber: 0.3.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-dataloader: 0.6.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-dns: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-document-load: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-express: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Bug Fixes

* span emit warnings on express instrumentation ([#1891](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1891)) ([f65f2f1](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/f65f2f1482f6f9ca80681f09249dc2b75ef7e3db))
</details>

<details><summary>instrumentation-fastify: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-fs: 0.9.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-generic-pool: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-graphql: 0.37.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
* **instrumentation-graphql:** add option to ignore resolver spans ([#1858](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1858)) ([c365375](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c365375ce2d35c01df06c96a4faf8d5a5d9d1ec3))
</details>

<details><summary>instrumentation-hapi: 0.34.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-ioredis: 0.37.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-knex: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-koa: 0.37.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-long-task: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-lru-memoizer: 0.34.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-memcached: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-mongodb: 0.39.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Bug Fixes

* **mongodb-example:** Ensure instrumentation is setup before mongoDB client is import ([#1851](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1851)) ([c54e9b6](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c54e9b61a031469110d845387ae1853b9197063d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-mongoose: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-mysql: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-mysql2: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-nestjs-core: 0.34.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-net: 0.33.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-pg: 0.38.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Bug Fixes

* **instrumentation-pg:** remove `@opentelemetry/core` from dependencies ([#1895](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1895)) ([c0d873c](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c0d873c360c00cd81a7c2ced74683f8408eabd84))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-pino: 0.35.0</summary>

### Features

* Allow configuring pino to log with different keys ([#1867](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1867)) ([33b31d0](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/33b31d055326d5fc1456bb46ebc2d7e888b376db))
* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-redis: 0.36.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-redis-4: 0.36.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Bug Fixes

* **instrumentation-redis-4:** fix multi.exec() instrumentation for redis &gt;=4.6.12 ([#1904](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1904)) ([fce7d3b](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/fce7d3b5e478ff7525c9ffe99e59bf35f8c06207))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-restify: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-router: 0.34.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-socket.io: 0.36.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-tedious: 0.7.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>instrumentation-user-interaction: 0.35.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>instrumentation-winston: 0.34.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))
</details>

<details><summary>@opentelemetry/propagation-utils: 0.30.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>@opentelemetry/resource-detector-alibaba-cloud: 0.28.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>@opentelemetry/resource-detector-aws: 1.3.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>@opentelemetry/resource-detector-azure: 0.2.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>@opentelemetry/resource-detector-container: 0.3.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>@opentelemetry/resource-detector-gcp: 0.29.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

<details><summary>resource-detector-instana: 0.6.0</summary>

### Features

* **deps:** update otel-js to 1.21.0/0.48.0 ([9624486](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/96244869d0fe22e6006fa6ef5e54839e06afb99d))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.35.1 to ^0.36.0
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by pichlermarc** [comment]
I would like to update OTel core before releasing, but since we're now using logs API packages too, the generated renovate PR will be incomplete. 

@open-telemetry/javascript-approvers, if you have some time, please take a look at #1897, it updates the renovate config to include a full list of experiemental packages. Thx! :slightly_smiling_face:

**Review by pichlermarc — APPROVED** [review]
Alright, let's get this merged.

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-alibaba-cloud-v0.28.6 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-aws-v1.3.6 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-container-v0.3.6 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-gcp-v0.29.6 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-instana-v0.6.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.41.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-web-v0.36.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/host-metrics-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/propagation-utils-v0.30.6 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-amqplib-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-cucumber-v0.3.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-dataloader-v0.6.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fs-v0.9.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-lru-memoizer-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongoose-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-socket.io-v0.36.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-lambda-v0.38.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.38.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-bunyan-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-cassandra-driver-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-connect-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-express-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fastify-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-generic-pool-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.37.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-hapi-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-ioredis-v0.37.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-knex-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-koa-v0.37.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-memcached-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongodb-v0.39.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mysql-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mysql2-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-nestjs-core-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-net-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pg-v0.38.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pino-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-v0.36.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-4-v0.36.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-restify-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-router-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-winston-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-document-load-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-long-task-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-user-interaction-v0.35.0 :sunflower:

**Pull request merged**
