### PR TITLE
chore: move opentelemetry-propagator-jaeger to core

### PR DESCRIPTION
**Pull request by jtmalinowski**
Move opentelemetry-propagator-jaeger from contrib to core (open-telemetry/opentelemetry-js#1931).
This is to enable turning on the jaeger propagator using ENV variables.
Default Node Tracer Provider needs to depend on Jaeger propagator.

## Which problem is this PR solving?
- Counterpart commit of open-telemetry/opentelemetry-js#1931
- unblocks open-telemetry/opentelemetry-js#1929

## Short description of the changes
- remove  propagators/opentelemetry-propagator-jaeger

### CODE REVIEW

**Comment by vmarchaud** [comment]
@jtmalinowski looks fine, however tests are failing :/

**Review by dyladan — APPROVED** [review]

**Review by vmarchaud — APPROVED** [review]

**Review by johnbley — APPROVED** [review]

**Comment by obecny** [comment]
@jtmalinowski can you please resolve conflicts ?, core PR has been merged, thx

**Comment by jtmalinowski** [comment]
@obecny done, but now tests are failing; seems unrelated to me, but if there's something I can do to help, let me know

**Comment by jtmalinowski** [comment]
Tests fail because of an issue with transitive dependencies, and they are failing similarly on other PRs.

**Review by obecny — APPROVED** [review]

**Pull request merged**
