### PR TITLE
feat: update experimental Otel deps to ^0.31.0

### PR DESCRIPTION
**Pull request by Flarna**
## Which problem is this PR solving?

Avoid duplicates of e.g. `@opentelemetry/instrumentation`.

## Short description of the changes

Depend on ^0.31.0 for experimental OTel packages because ^0.29.2 doesn't pick up 0.31.
This avoids duplicates of e.g. @opentelemetry/instrumentation in case latest is requested via
app package.json.

## Checklist

- [ ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.

### CODE REVIEW

**Comment by Flarna** [comment]
There seems to be some dependency issue in opentelemetry-resource-detector-github resulting in failing builds:

```
> @opentelemetry/resource-detector-github@0.27.0 compile /home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/detectors/node/opentelemetry-resource-detector-github
> tsc -p .
error TS2688: Cannot find type definition file for 'parse5'.
  The file is in the program because:
    Entry point for implicit type library 'parse5'
../../../node_modules/@types/jsdom/base.d.ts:4:33 - error TS7016: Could not find a declaration file for module 'parse5'. '/home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/node_modules/parse5/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/parse5` if it exists or add a new declaration (.d.ts) file containing `declare module 'parse5';`
4 import { ElementLocation } from "parse5"
```

@smithclay I think you added this detector but you are not mentioned as owner in https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/component_owners.yml.
Do you feel still responsible for it? Any hints how to fix this?

**Comment by Flarna** [comment]
back to draft as 0.30.0 is already outdated

**Review by vmarchaud — APPROVED** [review]

**Comment by dyladan** [comment]
I'm going to hold this until I can release the packages that have already been updated. #1112 is blocking that so please review that so we can get the previous release finished and we can get this through

**Review by dyladan — APPROVED** [review]

**Comment by dyladan** [comment]
Going to merge this but i'd like to do #1113 first since this touches so many packages. Would appreciate a review there.

**Pull request merged**
