### PR TITLE
chore: update component owner for AWS to jj22ee

### PR DESCRIPTION
**Pull request by jj22ee**
## Short description of the changes

- Followup of https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2415#issue-2500478070

Discussed within the X-Ray team at AWS, I will take over ownership+maintenance duties of the AWS components from @carolabadeer, whose bandwidth is currently being focused outside of OTel.

### CODE REVIEW

**Review by blumamir — APPROVED** [review]

**Review by pichlermarc — APPROVED** [review]
Awesome, welcome @jj22ee - happy to have you on-board :tada:

**Comment by pichlermarc** [comment]
@jj22ee have you considered joining the OTel Organization? That would allow us to auto-assign pull requests to you for the relevant packages. I'd gladly sponsor you joining the Org. :)

**Comment by jj22ee** [comment]
@pichlermarc Hey, thanks for approving this code-owner update. I do want to join the OTel Organization, thanks for offering to sponsor me to join. Please let me know what I need to do on my end to join.

**Comment by pichlermarc** [comment]
@jj22ee great to hear that. 🙌  Usually two sponsors from the organization are needed (from two different companies) - so you'd need to find one more person to sponsor you. You can find all the requirements to become a member [in the community repo](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#member).

Once you have found a second sponsor and opened the request as outlined in the doc I linked, you can ping me on the CNCF slack and I'll comment to say that I support your membership request. 🙂

**Comment by trentm** [comment]
Hi @jj22ee, I'm happy to be a second sponsor for you.

**Pull request merged**
