### PR TITLE
chore: bump otel dependencies to latest patch

### PR DESCRIPTION
**Pull request by dyladan**

### CODE REVIEW

**Review by vmarchaud — APPROVED** [review]
do you want to include this in the 0.15 contrib release ?

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
Would be be possible to use a bot for tasks like this? Currently renovate bot tries to update all deps in one shot but this easily fails.
Maybe create a dedicated config to update only otel core and one more for otel api?

**Comment by dyladan** [comment]
> Would be be possible to use a bot for tasks like this? Currently renovate bot tries to update all deps in one shot but this easily fails.
> Maybe create a dedicated config to update only otel core and one more for otel api?

likely possible. i'll look into it

**Comment by obecny** [comment]
you have missed propagators, examples, metapackages (auto), detectors

**Pull request merged**
