### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>auto-instrumentations-node: 0.43.0</summary>

### Features

* **auto-instrumentations-node:** enabling instrumentations via env ([#1953](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1953)) ([0656f37](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/0656f37634e1df71d68cc34cbd210abb6b4776d9))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.39.0 to ^0.39.1
    * @opentelemetry/instrumentation-express bumped from ^0.36.0 to ^0.36.1
    * @opentelemetry/instrumentation-graphql bumped from ^0.38.0 to ^0.38.1
    * @opentelemetry/instrumentation-mongodb bumped from ^0.40.0 to ^0.41.0
    * @opentelemetry/instrumentation-pg bumped from ^0.39.0 to ^0.39.1
</details>

<details><summary>instrumentation-aws-sdk: 0.39.1</summary>

### Bug Fixes

* **instr-aws-sdk:** ensure that instrumentation does not crash on bogus SQS.sendMessageBatch input ([#1999](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1999)) ([fa7e2f5](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/fa7e2f52d3869f8349895bcd3abb8cc428946cd1))
</details>

<details><summary>instrumentation-express: 0.36.1</summary>

### Bug Fixes

* **instr-express:** normalize paths with double slashes ([#1995](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1995)) ([65a9553](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/65a9553e76a3e61da71c31758b6e5320f286374b))
</details>

<details><summary>instrumentation-graphql: 0.38.1</summary>

### Bug Fixes

* **instrumentation-graphql:** limit support to &gt;=14 &lt;17 ([#1971](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1971)) ([ff40cc8](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/ff40cc83d2acae431e6ad97f7421e5a1d068615b))
</details>

<details><summary>instrumentation-mongodb: 0.41.0</summary>

### ⚠ BREAKING CHANGES

* **instrumentation-mongodb:** temporarily reduce supported range to mongodb <6.4 ([#1984](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1984))

### Bug Fixes

* **instrumentation-mongodb:** temporarily reduce supported range to mongodb &lt;6.4 ([#1984](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1984)) ([2d3bb52](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/2d3bb52762a637a4d0d0c14ff254eebc4fbbd508))
</details>

<details><summary>instrumentation-pg: 0.39.1</summary>

### Bug Fixes

* **instrumentation-pg:** prevent net.peer.port from being NaN ([#1982](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1982)) ([3b2090b](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/3b2090b5f53ee56e8d06ef7c144588141080804c))
</details>

<details><summary>instrumentation-runtime-node: 0.2.1</summary>

### Bug Fixes

* **instrumentation-runtime-node:** use TestMetricReader, unref timer ([#1965](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1965)) ([e24797e](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e24797e4211b4b39a55b1549e113a425226806b8))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by pichlermarc — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.43.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-runtime-node-v0.2.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-express-v0.36.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.38.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongodb-v0.41.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pg-v0.39.1 :sunflower:

**Pull request merged**
