### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>@opentelemetry/auto-instrumentations-node: 0.31.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.8.0 to ^0.8.1
    * @opentelemetry/instrumentation-ioredis bumped from ^0.30.0 to ^0.31.0
</details>

<details><summary>instrumentation-aws-sdk: 0.8.1</summary>

### Bug Fixes

* **aws-sdk:** avoid repeating MessageAttributeNames in sqs receiveMessage ([#1044](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1044)) ([4b4ded6](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/4b4ded6e5b781b9a9cb2c55102ec0949da062511))
</details>

<details><summary>instrumentation-ioredis: 0.31.0</summary>

### Features

* **ioredis:** only serialize non sensitive arguments in db statement attribute ([#1052](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1052)) ([375dfe0](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/375dfe07bcd88b8cfb0e6dc291dcc9fd3fba2f9e))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by weyert — APPROVED** [review]
LGTM

**Comment by dyladan** [comment]
We need to figure out what went wrong with the previous release before merging this one.

**Comment by MikeGoldsmith** [comment]
Any update on when we can expect the release to go out?

**Comment by masonjlegere** [comment]
Is this still going out?

**Comment by dyladan** [comment]
It needs an approving review @open-telemetry/javascript-approvers

**Review by MSNev — APPROVED** [review]

**Review by mwear — APPROVED** [review]

**Comment by dyladan** [comment]
Looks like the build is broken because of the autoinjection plugin which appears to be an unmaintained module

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.8.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-ioredis-v0.31.0 :sunflower:

**Pull request merged**
