### PR TITLE
feat(detector-github)!: change implementation to DetectorSync interface

### PR DESCRIPTION
**Pull request by david-luna**
## Context

Another PR moving away from the deprecated `Detector` interface in order to prepare the codebase for a fix for #2320. this time is for `GitHub` detector.

Not doing all detectors at once:
- detectors are independent from each other
- smaller PRs for faster reviews
- other detectors have a similar approach on exceptions like the described in #2328 

My reasons to categorize it as a refactor are:
- SDK handles both interfaces using `detectResources` from `@opentelemetry/resources` package. [Ref](https://github.com/open-telemetry/opentelemetry-js/blob/54b14fbbe33e0cf38115ee8c5c934a4e27786186/packages/opentelemetry-resources/src/detect-resources.ts#L32)
- it is unlikely to be used oustide the SDK or auto-instrumentations

## Short description of the changes

- change `detect` method to be sync

### CODE REVIEW

**Comment by pichlermarc** [comment]
I'll sponsor this.

**Review by pichlermarc — APPROVED** [review]
Thanks for updating this :+1:

**Comment by pichlermarc** [comment]
(changed the title to reflect that this is a breaking change :slightly_smiling_face:

**Comment by trentm** [comment]
@pichlermarc FYI: David was going to bring up some Qs regarding all the Detector -> DetectorSync PRs in the JS SIG tomorrow. There is some more discussion on https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2328

**Comment by david-luna** [comment]
> @pichlermarc FYI: David was going to bring up some Qs regarding all the Detector -> DetectorSync PRs in the JS SIG tomorrow. There is some more discussion on #2328

On the SIG we agreed to break for non stable detectors like this one. So I'm merging this one :)

**Pull request merged**
