### PR TITLE
docs: update readmes to follow a standard pattern

### LINKED ISSUE #819: Word the readmes better
Many of the packages have a section like that:

> This module provides automatic instrumentation for package name.
> For automatic instrumentation see the @opentelemetry/sdk-trace-node package.

Which reads very weird to me - both are kind of true, but in a different way.

https://github.com/open-telemetry/opentelemetry-js-contrib/pull/797#issuecomment-1001695501 suggested a better wording:

> This module provides automatic instrumentation for the ___ module, which may be loaded using the [@opentelemetry/sdk-trace-node](...url...) package and is included in the [@opentelemetry/auto-instrumentations-node](...url...) bundle.
>
> If total installation size is not constrained, it is recommended to use the [@opentelemetry/auto-instrumentations-node](...url...) bundle with [@opentelemetry/sdk-node](...url...) for the most seamless instrumentation experience.

Go over the readmes and fix the above occurrences.
Alternatively, we could figure out a better format for the README to avoid such tweaks in the future.

### PR DESCRIPTION
**Pull request by pizzaz93**
Covers the node folder portion of the issue in #819.

Fixes #819

### CODE REVIEW

**Comment by pizzaz93** [comment]
Validating the first file commit before propagating the edit to other files, @blumamir feel free to disregard for the moment.

**Comment by pizzaz93** [comment]
Meaning that the package is  listed under the "Supported instrumentations" header?
[https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node
](https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node
)

What wording would we want for the `web` folder?

**Comment by Rauno56** [comment]
> Meaning that the package is listed under the "Supported instrumentations" header? [https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node ](https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node)

In the readme, yes, and under `dependencies` in the `package.json`.

> What wording would we want for the `web` folder?

What would make sense in your opinion?

**Comment by pizzaz93** [comment]
`fs`, `tedious`, `router`  aren't included in https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node

I don't think I have sufficient context to suggest verbiage for the `web` folder content edits.

**Comment by Rauno56** [comment]
> fs, tedious, router aren't included in https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node

Added those: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/981
Thanks for going over them!

> I don't think I have sufficient context to suggest verbiage for the web folder content edits.

I'd use something very analogous:

>  This module provides automatic instrumentation for [...], which may be loaded using the [`@opentelemetry/sdk-trace-web`](https://www.npmjs.com/package/@opentelemetry/sdk-trace-web) package.
>
> If total installation size is not constrained, it is recommended to use the [`@opentelemetry/auto-instrumentations-web`](https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-web) bundle with [@opentelemetry/sdk-trace-web](https://www.npmjs.com/package/@opentelemetry/sdk-trace-web) for the most seamless instrumentation experience.

**Comment by pizzaz93** [comment]
> > fs, tedious, router aren't included in https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node
> 
> Adding those: #981 Thanks for going over them!
> 
> > I don't think I have sufficient context to suggest verbiage for the web folder content edits.
> 
> I'd use something very analogous:
> 
> > This module provides automatic instrumentation for [...], which may be loaded using the [`@opentelemetry/sdk-trace-web`](https://www.npmjs.com/package/@opentelemetry/sdk-trace-web) package.
> > If total installation size is not constrained, it is recommended to use the [`@opentelemetry/auto-instrumentations-web`](https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-web) bundle with [@opentelemetry/sdk-trace-web](https://www.npmjs.com/package/@opentelemetry/sdk-trace-web) for the most seamless instrumentation experience.

Thank you @Rauno56, I've added the updated readme introduction syntax to the `web` folder as well.

**Review by Rauno56 — APPROVED** [review]
Nice! Thanks and congrats for the first contribution!

**Comment by pizzaz93** [comment]
It's been two months since this PR was first filed, is this stuck on the dependent PR?

**Review by blumamir — APPROVED** [review]
LGTM
Sorry about the delay and thanks for the reminder :)

**Comment by pizzaz93** [comment]
Thank you @Rauno56 and @blumamir.

**Pull request merged**
