### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@opentelemetry/instrumentation-aws-sdk: 0.2.0</summary>

### Features

* AWS-SDK SNS Context propagation ([#728](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/728)) ([78cd4e1](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/78cd4e118e5a41107d84dfd1ae8c4c28e885b27e))
</details>
<details><summary>@opentelemetry/instrumentation-graphql: 0.26.1</summary>

### Bug Fixes

* adding nested input variables in graphql plugin ([#720](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/720)) ([7a7d3a3](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/7a7d3a35e66678cf7d11fb9c89b8a26f2d4bfd6b))
</details>
<details><summary>@opentelemetry/instrumentation-nestjs-core: 0.27.0</summary>

### Features

* report `path` and `route` with fastify backend in nestjs-core instrumentation ([#714](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/714)) ([62a04c7](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/62a04c7a7d640393c31ae357131bfca766c1f3fb))
</details>
<details><summary>@opentelemetry/auto-instrumentations-node: 0.26.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-graphql bumped from ^0.26.0 to ^0.26.1
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by dyladan** [comment]
@Rauno56 if you approve I can release this since it only affects one package

**Review by Rauno56 — APPROVED** [review]

**Comment by dyladan** [comment]
@NathanielRN @willarmiros can you confirm the version 0.2.0 is correct for aws?

**Comment by dyladan** [comment]
Looks like the action is clearing old reviews. I'll see what i can do to stop that from happening.

**Comment by willarmiros** [comment]
@dyladan yep that's ok, instrumentation is still non-stable, the other AWS packages (id generator, propagator, resource detectors) are stable.

**Review by blumamir — APPROVED** [review]

**Comment by blumamir** [comment]
There is nothing preventing this PR from being merged, right?
I would really be glad to publish the aws-sdk instrumentation with the sns context propagation inject feature.

**Comment by dyladan** [comment]
Sorry this took so long to merge

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/auto-instrumentations-node is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.26.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-aws-sdk is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.2.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-graphql is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.26.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-nestjs-core is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-nestjs-core-v0.27.0 :sunflower:

**Pull request merged**
