### PR TITLE
feat: update docker-related scripts and document docker engine prerequisite

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
## Which problem is this PR solving?

- Compose is now part of the `docker` cli, and can be used by running `docker compose` instead of `docker-compose`.

## Short description of the changes

- Updates fastify example docker-related scripts so they use `docker compose` instead of `docker-compose`. 
- Update README so Docker Engine is listed as a prerequisite.

### CODE REVIEW

**Review by osherv — APPROVED** [review]

**Review by blumamir — COMMENTED** [review]
Thank you for the fix.
I wonder if using `docker-compose` fails for the new docker clis, as this change might now confuse users with old cli versions that not yet support the new syntax.

WDYT?

**Comment by patrickocoffeyo** [comment]
@blumamir You make a good point, I updated the readme with instructions to install docker, perhaps I should add a note about ensuring docker is up to date?

**Comment by blumamir** [comment]
> @blumamir You make a good point, I updated the readme with instructions to install docker, perhaps I should add a note about ensuring docker is up to date?

Yes. If it is possible to find the minimum supported docker cli version for this syntax and add it to the `Prerequisites` that would be best

**Comment by pichlermarc** [comment]
Thanks for your contribution :slightly_smiling_face: 

> > @blumamir You make a good point, I updated the readme with instructions to install docker, perhaps I should add a note about ensuring docker is up to date?
> 
> Yes. If it is possible to find the minimum supported docker cli version for this syntax and add it to the `Prerequisites` that would be best

Looks like we could add
 - a minimum Docker Desktop version ([4.12.0 maybe?](https://docs.docker.com/desktop/release-notes/#4120))
 - a note to install `docker-compose-plugin` for Docker Engine users with an existing installation :slightly_smiling_face: 

I had an existing (and up-to date) installation of Docker Engine for Linux, turns out it's the plugin that I had to install. :slightly_smiling_face:

**Comment by blumamir** [comment]
@patrickocoffeyo are you still working on this? should we keep it open?

**Comment by patrickocoffeyo** [comment]
@blumamir my apologies, this dropped off my radar. I'll update this later today, thank you for the reminder!

**Review by blumamir — APPROVED** [review]

**Pull request merged**
