### PR TITLE
fix(koa): fix instrumentation of ESM-imported koa

### PR DESCRIPTION
**Pull request by chentsulin**
## Which problem is this PR solving?

- ESM-imported koa is not patched by instrumentation.

## Short description of the changes

- Use the same approach introduced in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1694

### CODE REVIEW

**Review by david-luna — APPROVED** [review]

**Comment by pichlermarc** [comment]
Hi, thanks for your contribution and sorry for the late review. #

#1735 introduced a simple way to test if everything is working as intended with ESM instrumentations. Would you mind adding this to this PR as well?

**Comment by chentsulin** [comment]
Hi @pichlermarc, I failed to create a proper test case based on the #1735 PR. Is there anyone can help?

**Comment by trentm** [comment]
I can help add a test case.

**Review by trentm — APPROVED** [review]

**Review by JamieDanielson — APPROVED** [review]
Thanks for this!

**Comment by trentm** [comment]
Thanks for the reviews. I turned on the TAV tests here and I see that they fail, so I may need to dig into that. It might be a separate issue, though.

**Comment by trentm** [comment]
Thanks @chentsulin!

**Pull request merged**
