### PR TITLE
ioredis and redis DB semantic conventions

### PR DESCRIPTION
**Pull request by naseemkullah**
towards https://github.com/open-telemetry/opentelemetry-js-contrib/issues/116

Want to do this one first, will likely follow up with more.

N.B. Now nothing in attributes points to which specific library (e.g.: ioredis) is being traced.

### CODE REVIEW

**Comment by naseemkullah** [comment]
typedocs 😍 
image

**Comment by naseemkullah** [comment]
What to do about

```
test/userInteraction.nozone.test.ts:48:39 - error TS2345: Argument of type 'ZoneContextManager' is not assignable to parameter of type 'ContextManager'.
  The types returned by 'active()' are incompatible between these types.
    Type 'import("/root/project/plugins/web/opentelemetry-plugin-user-interaction/node_modules/@opentelemetry/context-base/build/src/context").Context' is not assignable to type 'import("/root/project/plugins/web/opentelemetry-plugin-user-interaction/node_modules/@opentelemetry/api/node_modules/@opentelemetry/context-base/build/src/context").Context'.
      Types have separate declarations of a private property '_currentContext'.

48       context.setGlobalContextManager(contextManager);
                                         ~~~~~~~~~~~~~~

test/userInteraction.test.ts:51:39 - error TS2345: Argument of type 'ZoneContextManager' is not assignable to parameter of type 'ContextManager'.

51       context.setGlobalContextManager(contextManager);
```

?

**Comment by naseemkullah** [comment]
Now includes redis as well...

**Comment by dyladan** [comment]
I'm not sure about the build failure, but my best guess is that you bumped the core versions for some, but not all, of the main packages. i would revert those changes as they are not relevant here.

**Comment by naseemkullah** [comment]
> I'm not sure about the build failure, but my best guess is that you bumped the core versions for some, but not all, of the main packages. i would revert those changes as they are not relevant here.

Very well, I'll let renovate bot do it's job!

**Comment by naseemkullah** [comment]
Still failing despite leaving unrelated packages alone


```

> @opentelemetry/plugin-user-interaction@0.9.0 version:update /root/project/plugins/web/opentelemetry-plugin-user-interaction
> node ../../../scripts/version-update.js

test/userInteraction.nozone.test.ts:48:39 - error TS2345: Argument of type 'ZoneContextManager' is not assignable to parameter of type 'ContextManager'.
  The types returned by 'active()' are incompatible between these types.
    Type 'import("/root/project/plugins/web/opentelemetry-plugin-user-interaction/node_modules/@opentelemetry/context-base/build/src/context").Context' is not assignable to type 'import("/root/project/plugins/web/opentelemetry-plugin-user-interaction/node_modules/@opentelemetry/api/node_modules/@opentelemetry/context-base/build/src/context").Context'.
      Types have separate declarations of a private property '_currentContext'.

48       context.setGlobalContextManager(contextManager);
                                         ~~~~~~~~~~~~~~

test/userInteraction.test.ts:51:39 - error TS2345: Argument of type 'ZoneContextManager' is not assignable to parameter of type 'ContextManager'.

51       context.setGlobalContextManager(contextManager);
                                         ~~~~~~~~~~~~~~


Found 2 errors.
```

**Pull request merged**
