### PR TITLE
feature: Graphql

### LINKED ISSUE #14: GraphQL Apollo Server
**Is your plugin request related to a problem? Please describe.**
GraphQL batches multiple queries and entities as a data access protocol into a single HTTP request.
In the background, the GraphQL server will run multiple so-called resolvers that return data for a specific chunk of the graph to fulfill these GraphQL queries. Resolvers can run parallel and depend on each other while they usually fetch data from downstream services or from databases using [data-loader](https://github.com/graphql/dataloader) concept which makes the data orchestration even more complex. Understanding this execution with timing and error is crucial to debug and optimize GraphQL servers.

https://blog.apollographql.com/graphql-explained-5844742f195e

[Apollo Server](https://www.apollographql.com/docs/apollo-server/) is probably the most popular library to run GraphQL in production.

Commercial alternative for GraphQL Apollo Tracing
https://blog.apollographql.com/the-new-trace-view-in-apollo-engine-566b25bdfdb0

**Is it applicable for Node or Browser or both**
Node.js only.

**Do you expect this plugin to be commonly used**
Yes
Weekly Downloads:  don't know the exact number

**Additional context**

- GraphQL Tracing format could may solve this in a more general way and provide compatibility for all GraphQL engines: https://github.com/apollographql/apollo-tracing

### PR DESCRIPTION
**Pull request by obecny**
## Which problem is this PR solving?

- Adding graphql instrumentation
- Fixes #14 

## Short description of the changes

- It instruments the graphql library
- Added example of using Apollo Server and Express Graphql - 2 most popular lib.

### CODE REVIEW

**Review by dyladan — APPROVED** [review]
I already reviewed this when the PR was open in the main repo but I'll put the same comment here.

I'm not familiar with the graphql module's API, but it seems like a generally straightforward implementation of the tracing and the use of the new instrumentation module looks good to me. Approving.

**Review by vmarchaud — APPROVED** [review]

**Comment by tvvignesh** [comment]
@obecny Thanks a lot for this. Just looked up on NPM and I am not able to find the package `@opentelemetry/instrumentation-graphql` - Is it yet to be pushed?

**Comment by obecny** [comment]
> @obecny Thanks a lot for this. Just looked up on NPM and I am not able to find the package `@opentelemetry/instrumentation-graphql` - Is it yet to be pushed?

it hasn't been released yet 

> 
> Also, does this support Apollo Federation? Thanks

Not sure, the plugin instruments the graphql core library, so anything that is using that should be instrumented the same. but if certain library does something more beyond the graphql lib then not

**Comment by PacoDu** [comment]
> > @obecny Thanks a lot for this. Just looked up on NPM and I am not able to find the package `@opentelemetry/instrumentation-graphql` - Is it yet to be pushed?
> 
> it hasn't been released yet

Could we know when this will be released ? Can't wait to try it out !

**Comment by Hongbo-Miao** [comment]
Just saw it published six days ago.
Tested and it works great, thanks @obecny !

**Comment by carlitux** [comment]
@obecny any suggestion to debug?, I have all set up done but nothing is traced.

**Comment by obecny** [comment]
> @obecny any suggestion to debug?, I have all set up done but nothing is traced.

Please create an issue and fill out all needed information including code samples etc. otherwise it is impossible to tell anything

**Pull request merged**
