### PR TITLE
refactor(instr-cassandra-driver): use exported strings for attributes

### PR DESCRIPTION
**Pull request by david-luna**
## Which problem is this PR solving?

- Updates #2025 

## Short description of the changes

- Update @opentelemetry/semantic-conventions to ^1.22
- Replace `SemanticAttributes.*` with exported strings `SEMATTRS_*`
- Update README with new semantic convention package version and key

### CODE REVIEW

**Review by trentm — APPROVED** [review]

**Review by blumamir — APPROVED** [review]

**Comment by blumamir** [comment]
this is ready to merge, but for some reason the TAV test fails with this message:

```
Run npm run --if-present --workspaces test-all-versions -w @opentelemetry/instrumentation-cassandra
npm ERR! No workspaces found:
npm ERR!   --workspace=@opentelemetry/instrumentation-cassandra

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2024-04-[29](https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/8874128142/job/24361069901?pr=2139#step:9:30)T06_22_44_086Z-debug-0.log
Error: Process completed with exit code 1.
```

The changes seems unrelated, but the error does mention "npm ERR!   --workspace=@opentelemetry/instrumentation-cassandra" so I guess something is broken in the build?
any ideas?

**Comment by JamieDanielson** [comment]
Hm it looks like cassandra is one of the few instrumentations that doesn't have a "tav" script so I guess it should be skipped in this test? What's weird though is I would've expected #2099 to fail too then because it also doesn't have tav. 🤔

**Comment by trentm** [comment]
> What's weird though is I would've expected #2099 to fail too then because it also doesn't have tav. 🤔

The TAV workflow didn't run on that PR. For some reason the "TAV for PR" didn't trigger. I don't know why. Hrm.
However, even if it had, it would have passed:

```
% npm run --if-present --workspaces test-all-versions -w @opentelemetry/instrumentation-router
%
```

---

The issue with instr-cassandra is confusion with the dir name and issue label using "instrumentation-cassandra", but the package actually being `instrumentation-cassandra-driver`.

If there are multiple workspace args, then I think it all works:

```
% npm run --if-present --workspaces test-all-versions -w @opentelemetry/instrumentation-cassandra -w @opentelemetry/instrumentation-hapi

> @opentelemetry/instrumentation-hapi@0.37.0 test-all-versions
> tav
...
```

So this will only happen on a PR that *only* has the `pkg:instr-cassandra` label -- which hasn't happened before (https://github.com/open-telemetry/opentelemetry-js-contrib/issues?q=label%3Apkg%3Ainstrumentation-cassandra+).


# fix

I'll try to fix with:

1. This patch:
```diff
--- a/.github/component-label-map.yml
+++ b/.github/component-label-map.yml
@@ -71,7 +71,7 @@ pkg:instrumentation-bunyan:
   - changed-files:
       - any-glob-to-any-file:
           - plugins/node/opentelemetry-instrumentation-bunyan/**
-pkg:instrumentation-cassandra:
+pkg:instrumentation-cassandra-driver:
```

2. and changing the label name to have "-driver".

**Comment by trentm** [comment]
> 2\. and changing the label name to have "-driver".

Oh, there are already both label names: https://github.com/open-telemetry/opentelemetry-js-contrib/labels?q=cassandra

Screenshot 2024-04-30 at 7 15 41 PM

I'll update all to the one we want and delete the other package label.

**Comment by trentm** [comment]
> delete the other package label.

We'll have to wait to delete the other package label until after this change goes in, because the github action adding component labels is re-adding it.

**Pull request merged**
