### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>auto-configuration-propagators: 0.2.0</summary>

### Features

* Add package for automatic propagator configuration ([#2299](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2299)) ([4bb28c9](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/4bb28c99c29b52193bcd9d0f14202beac6c5dfa6))
</details>

<details><summary>auto-instrumentations-node: 0.49.0</summary>

### Features

* **auto-instrumentations-node:** enable auto-instrumentation for KafkaJS ([#2340](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2340)) ([8302464](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/830246460beed0ece9c61852675943bb86161692))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-amqplib bumped from ^0.39.0 to ^0.40.0
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.43.0 to ^0.43.1
    * @opentelemetry/instrumentation-express bumped from ^0.41.0 to ^0.41.1
    * @opentelemetry/instrumentation-knex bumped from ^0.38.0 to ^0.39.0
</details>

<details><summary>instrumentation-amqplib: 0.40.0</summary>

### Features

* Add the ability to use span links when consuming a message amqp plugin ([#1972](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1972)) ([5f2c160](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/5f2c160ac0fd4f6aa76c227537c34329c6c9dfb2))
</details>

<details><summary>instrumentation-aws-sdk: 0.43.1</summary>

### Bug Fixes

* **aws-sdk:** add http status code attribute to aws sdk span if aws sdk v3 client exception occurs ([#2344](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2344)) ([9a06381](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/9a06381afc6a7a27bc49af4ef796a547eafbf6ff))
</details>

<details><summary>instrumentation-express: 0.41.1</summary>

### Bug Fixes

* **instr-express:** fix handler patching for already patched router ([#2294](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2294)) ([2c32e58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/2c32e5869ef9b6d582ba4da02623a030309bcaf3))
</details>

<details><summary>instrumentation-knex: 0.39.0</summary>

### Features

* **instr-knex:** implement requireParentSpan config flag ([#2288](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2288)) ([6e8989d](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/6e8989de4d60c32bc9b3e3ef760e92c68ae7f491))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by JamieDanielson — APPROVED** [review]

**Review by trentm — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-configuration-propagators-v0.2.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.49.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.43.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-express-v0.41.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-knex-v0.39.0 :sunflower:

**Pull request merged**
