### PR TITLE
chore: add a few packages to release config

### PR DESCRIPTION
**Pull request by Flarna**
## Which problem is this PR solving?

Release please doesn't release all packages.

Refs: #871

## Short description of the changes

Added opentelemetry-propagation-utils, opentelemetry-instrumentation-fastify and opentelemetry-instrumentation-long-task to release config.

## Checklist

- [ ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.

### CODE REVIEW

**Review by dyladan — APPROVED** [review]

**Review by vmarchaud — APPROVED** [review]

**Comment by Flarna** [comment]
It seems adding a package to release config doesn't trigger a release.
Looking into #871 it's maybe a good idea to trigger a release manually. Or do we need a dummy commit in fastify instrumentation to get this done?

**Comment by dyladan** [comment]
I think you actually need to add them to the manifest https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.release-please-manifest.json

**Comment by dyladan** [comment]
There are 2 files for some reason. The manifest tracks the currently released versions and the config tracks where the packages exist in the directory tree

**Comment by Flarna** [comment]
Hmm, I was doing the same as #840 did for tedious which was finally included by #815 and tedious was added in .release-please-manifest by the release main PR.

**Pull request merged**
