### PR TITLE
fix(redis-4): add support to new version of redis

### PR DESCRIPTION
**Pull request by osherv**
In the new version of @redis/client (1.4.2) they changed the function name of the function that we wrap (multi-->MULTI)

Link for the [CI](https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/3646626475/jobs/6157912674).

Link for the new [redis](https://github.com/redis/node-redis/compare/client%401.4.1...client%401.4.2).

### CODE REVIEW

**Comment by blumamir** [comment]
Have you taken a look at why the `net.peer.name` is not captured?
removing the entire support for instrumentation just because of this single attribute is not ideal. Maybe it's an easy fix?

**Comment by osherv** [comment]
@blumamir after digging into the issue, found the problem and fixed :)

**Review by blumamir — APPROVED** [review]
Thanks 🥇 
Can you please also add it to the unpatch section?

**Comment by osherv** [comment]
@blumamir oh right, sure!

**Review by blumamir — APPROVED** [review]

**Pull request merged**
