### PR TITLE
docs: update contributing guidelines for required org membership

### PR DESCRIPTION
**Pull request by JamieDanielson**
## Which problem is this PR solving?

It should be easier to auto-assign issues and PRs and grant more authority to codeowners on specific packages.
This came up while reviewing the [react-native instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2359#pullrequestreview-2458980329), which is currently the top requested feature in the repo. We want to delegate responsibly, while still [keeping a high bar for adding instrumentations](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2259).

## Short description of the changes

Update contributing guidelines to

- require membership in the OpenTelemetry org
- add owners to js-contrib-triagers role ([role request in community repo](https://github.com/open-telemetry/community/issues/2455))

### CODE REVIEW

**Comment by trentm** [comment]
Isn't https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/component-owners.yml already meant to be handling assigning PRs to and/or request reviews from component owners?  

From https://github.com/dyladan/component-owners#readme

> Automatically add component owners as assignees and approvers to pull requests.
>
> This works very similarly to CODEOWNERS, however with CODEOWNERS all owners must have write access to the repository. ...

**Comment by pichlermarc** [comment]
> This works very similarly to CODEOWNERS, however with CODEOWNERS all owners must have write access to the repository. ...

Aah, yes I completely forgot about this 🤦 `CODEOWNERS` does not work with non-write permission owners. 😞
 
Anyway I think we can still do something similar with `component-owners.yaml` and since we will give owners triage permissions they can then apply a label that a PR is ready to merge. Then approvers/maintainers can just swoop in and merge the PR. 🙂

**Comment by JamieDanielson** [comment]
@trentm @pichlermarc I removed the references to CODEOWNERS and just kept in the triagers role and the requirement of being in otel org.

**Review by pichlermarc — APPROVED** [review]
thank you for updating this and for going through the process or requesting the creation contrib triagers role 🙂

**Pull request merged**
