### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>auto-instrumentations-node: 0.34.0</summary>

### Features

* add new instrumentations into `auto-instrumentations-node` ([#981](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/981)) ([a00f390](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a00f390977a3091b068cf1485e7596b4133ea5d8))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-aws-lambda bumped from ^0.33.0 to ^0.33.1
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.9.2 to ^0.9.3
    * @opentelemetry/instrumentation-bunyan bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-cassandra-driver bumped from ^0.30.0 to ^0.31.0
    * @opentelemetry/instrumentation-connect bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-dataloader bumped from ^0.2.0 to ^0.2.1
    * @opentelemetry/instrumentation-dns bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-express bumped from ^0.31.2 to ^0.31.3
    * @opentelemetry/instrumentation-fs bumped from ^0.5.0 to ^0.5.1
    * @opentelemetry/instrumentation-fastify bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-graphql bumped from ^0.31.0 to ^0.32.0
    * @opentelemetry/instrumentation-hapi bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-ioredis bumped from ^0.32.1 to ^0.32.2
    * @opentelemetry/instrumentation-knex bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-koa bumped from ^0.32.0 to ^0.33.0
    * @opentelemetry/instrumentation-memcached bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-mongodb bumped from ^0.32.1 to ^0.32.2
    * @opentelemetry/instrumentation-mongoose bumped from ^0.31.0 to ^0.31.1
    * @opentelemetry/instrumentation-mysql bumped from ^0.31.0 to ^0.31.2
    * @opentelemetry/instrumentation-mysql2 bumped from ^0.32.0 to ^0.32.1
    * @opentelemetry/instrumentation-nestjs-core bumped from ^0.31.0 to ^0.31.1
    * @opentelemetry/instrumentation-net bumped from ^0.30.1 to ^0.30.2
    * @opentelemetry/instrumentation-pg bumped from ^0.31.1 to ^0.32.0
    * @opentelemetry/instrumentation-pino bumped from ^0.32.0 to ^0.32.1
    * @opentelemetry/instrumentation-redis bumped from ^0.33.0 to ^0.33.1
    * @opentelemetry/instrumentation-redis-4 bumped from ^0.33.0 to ^0.33.1
    * @opentelemetry/instrumentation-restify bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-router bumped from ^0.30.0 to ^0.31.0
    * @opentelemetry/instrumentation-tedious bumped from ^0.4.0 to ^0.4.1
    * @opentelemetry/instrumentation-winston bumped from ^0.30.0 to ^0.30.1
</details>

<details><summary>auto-instrumentations-web: 0.30.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-document-load bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-user-interaction bumped from ^0.31.0 to ^0.31.1
</details>

<details><summary>id-generator-aws-xray: 1.1.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
</details>

<details><summary>instrumentation-aws-lambda: 0.33.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/propagator-aws-xray bumped from ^1.1.0 to ^1.1.1
</details>

<details><summary>instrumentation-aws-sdk: 0.9.3</summary>

### Bug Fixes

* **aws-sdk:** bump aws-sdk instrumentation version to align with previous release ([#1247](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1247)) ([fd2480a](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/fd2480a4ea7b4093da523ecbc30743a55f38ab6c))
</details>

<details><summary>instrumentation-bunyan: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-cassandra-driver: 0.31.0</summary>

### Features

* **cassandra-responsehook:** added response hook to execute func ([#1180](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1180)) ([20767c4](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/20767c4fffee34bc51392894001bbb667576e91d))

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-connect: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-dataloader: 0.2.1</summary>

### Bug Fixes

* remove types of the instrumented libs form public apis ([#1221](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1221)) ([682d610](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/682d6107b7285829bb72e592936c585ccdfab16a))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-dns: 0.30.1</summary>

### Bug Fixes

* **dns:** remove lookupPromise polyfill for node8 dns promise tests  ([#1223](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1223)) ([2777a79](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/2777a793239018b968519f27d2d188e41a05afa9))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-document-load: 0.30.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-express: 0.31.3</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-fastify: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-fs: 0.5.1</summary>

### Bug Fixes

* **instrumentation-fs:** fix `fs.exists` when it's util.promisified ([#1222](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1222)) ([180b336](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/180b336ab482f7656e51e5949b26f36d9ce70ed5))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-graphql: 0.32.0</summary>

### Features

* support `graphql` v16 ([#998](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/998)) ([5da46ef](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/5da46ef7a29bbc64f600d794b1e68bb6738a9f2e))

### Bug Fixes

* **graphql:** graphql instrumentation throw for sync calls ([#1254](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1254)) ([524d98e](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/524d98e4fac3322b7da3cc865f53043f03f67bb7))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-hapi: 0.30.1</summary>

### Bug Fixes

* allow hapi plugin from array to be registered as argument ([#1253](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1253)) ([1db3b7e](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/1db3b7e7aa15fc0759264535752b771abff81feb))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-ioredis: 0.32.2</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-knex: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-koa: 0.33.0</summary>

### Features

* **koa:** add layer type to request hook context ([#1226](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1226)) ([6300733](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/6300733ddfa7357546500782d83d63320c134013))

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-long-task: 0.31.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-memcached: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-mongodb: 0.32.2</summary>

### Bug Fixes

* **mongodb:** use net.peer namespace for mongo host and port ([#1257](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1257)) ([c63d2a4](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c63d2a4206b8d4ba0fb337b253ff6c84f0814a09))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-mongoose: 0.31.1</summary>

### Bug Fixes

* remove types of the instrumented libs form public apis ([#1221](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1221)) ([682d610](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/682d6107b7285829bb72e592936c585ccdfab16a))
</details>

<details><summary>instrumentation-mysql: 0.31.2</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-mysql2: 0.32.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-nestjs-core: 0.31.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-net: 0.30.2</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-pg: 0.32.0</summary>

### Features

* **pg:** add requireParentSpan option ([#1199](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1199)) ([a6f054d](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a6f054de256acc3415deb8137c7ea4bd6926c08d))

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-pino: 0.32.1</summary>

### Bug Fixes

* Add applying patch debug log to pino module ([#1225](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1225)) ([a2719c5](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a2719c5fe4422b2264ad82c6c28bdd00dc06f4a4))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-redis: 0.33.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-redis-4: 0.33.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-restify: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-router: 0.31.0</summary>

### Features

* add new instrumentations into `auto-instrumentations-node` ([#981](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/981)) ([a00f390](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a00f390977a3091b068cf1485e7596b4133ea5d8))

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-tedious: 0.4.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-user-interaction: 0.31.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>instrumentation-winston: 0.30.1</summary>

### Bug Fixes

* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>plugin-react-load: 0.28.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
* separate public and internal types for all instrumentations ([#1251](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1251)) ([e72ea58](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e72ea58cfb888a90590970f63d3a042a8ea3aaf2))
</details>

<details><summary>propagator-aws-xray: 1.1.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
</details>

<details><summary>propagator-instana: 0.2.1</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
</details>

<details><summary>propagator-ot-trace: 0.26.2</summary>

### Bug Fixes

* address webpack memory issue for browser tests ([#1264](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1264)) ([c7f08fe](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/c7f08fed51bca68b0c522769c3c589102b98ec93))
</details>

<details><summary>resource-detector-aws: 1.2.0</summary>

### Features

* Implement experimental AWS ECS resource attributes ([#1083](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1083)) ([bea8a55](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/bea8a554de6ef5678a9968bb0f11c140cba7062a))
</details>

<details><summary>resource-detector-container: 0.2.0</summary>

### Features

* container ID detector for cgroup v2 ([#1181](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1181)) ([502caae](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/502caae17be17e20ee81189dbf79ca25121c7cfe))
* upstream mocha instrumentation testing plugin from ext-js [#621](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/621) ([#669](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/669)) ([a5170c4](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a5170c494706a2bec3ba51e59966d0ca8a41d00e))
</details>

<details><summary>resource-detector-gcp: 0.27.3</summary>

### Bug Fixes

* **deps:** update dependency gcp-metadata to v5 ([#1009](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1009)) ([d0a10eb](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/d0a10ebefbe3954e3a9b34e26e391eb73b53fb20))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by ryan-codaio** [comment]
Is there any guess for when this might be merged? I'm looking forward to being able to use #1199 in our app, and haven't been able to figure out how to get yarn to install the @opentelemetry/instrumentation-pg package from my Github fork instead of npm. Just wondering :)

**Comment by pavlospt** [comment]
Hello @dyladan , is there a roadmap for this release with any expected landing date?

**Review by vmarchaud — APPROVED** [review]

**Comment by luismiramirez** [comment]
Any news on this release? We're looking forward to using some new features and fixes.

**Comment by vmarchaud** [comment]
cc @open-telemetry/javascript-approvers it seems some people are waiting on this release, could we get a couple of look ?

**Comment by dyladan** [comment]
@vmarchaud all changes in this PR are already approved in other places. I usually just look to make sure the versions make sense and merge. Just need a single approval for that.

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-aws-v1.2.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-container-v0.2.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-gcp-v0.27.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-web-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-dataloader-v0.2.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fs-v0.5.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongoose-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-tedious-v0.4.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-lambda-v0.33.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.9.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-bunyan-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-cassandra-driver-v0.31.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-connect-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-dns-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-express-v0.31.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fastify-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.32.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-hapi-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-ioredis-v0.32.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-knex-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-koa-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-memcached-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongodb-v0.32.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mysql-v0.31.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mysql2-v0.32.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-nestjs-core-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-net-v0.30.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pg-v0.32.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pino-v0.32.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-v0.33.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-4-v0.33.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-restify-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-router-v0.31.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-winston-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-document-load-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-long-task-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-user-interaction-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/plugin-react-load-v0.28.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/propagator-aws-xray-v1.1.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/propagator-instana-v0.2.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/propagator-ot-trace-v0.26.2 :sunflower:

**Comment by vmarchaud** [comment]
> @vmarchaud all changes in this PR are already approved in other places. I usually just look to make sure the versions make sense and merge. Just need a single approval for that.

Yeah i knew about that but i'm not confident enough on the contrib part so choose to make a release ^^

**Pull request merged**
