### PR TITLE
chore: remove skipLibCheck: true from tsconfigs where it is not necessary

### PR DESCRIPTION
**Pull request by pichlermarc**
`skipLibCheck: true` is set a few instrumentation libraries, even though they're not necessary anymore. The only remaining instrumentation that needs it is `@opentelemetry/instrumentation-lru-memoizer`.

### CODE REVIEW

**Review by david-luna — APPROVED** [review]
> even though they're not necessary anymore...

LGTM but could I get more context on this? Thanks!

**Comment by pichlermarc** [comment]
> > even though they're not necessary anymore...
> 
> LGTM but could I get more context on this? Thanks!

We've seen this cause some confusion over at #1985. 

It looks like some instrumentations had set `skipLibCheck: true`. I assume this to be either an unintentional copy-paste from an existing instrumentation that had this option set, or it was necessary back then due to actually missing types. Either way, nowadays, the instrumentation compile fine without that flag, so I think it's best to revert to the more common strict config that we use.

**Review by blumamir — APPROVED** [review]

**Comment by blumamir** [comment]
> The only remaining instrumentation that needs it is `@opentelemetry/instrumentation-lru-memoizer`.

curious why this instrumentation still need the setting

**Comment by pichlermarc** [comment]
> > The only remaining instrumentation that needs it is `@opentelemetry/instrumentation-lru-memoizer`.
> 
> curious why this instrumentation still need the setting

There's some problem with the `lru-cache` types. I looked into it briefly but couldn't find any way to resolve the situation. I think this may be a problem with the upstream packages we use.

**Pull request merged**
