### PR TITLE
feat: support using lambda context in the aws lambda context extractor

### PR DESCRIPTION
**Pull request by chrisrichardsevergreen**
## Which problem is this PR solving?
Implements feat #855 - it exposes the lambda context object to the custom event extractor to allow this to carry context.

## Short description of the changes

- Changes the signature of the eventContextExtractor to add context as a second argument
- Passes this through in via _determineParent
- Updates tests and README

## Checklist
- [x ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.

### CODE REVIEW

**Review by willarmiros — APPROVED** [review]
LGTM! Definitely a reasonable addition.

**Comment by blumamir** [comment]
hi @chrisrichardsevergreen ,
Can you please fix your CLA so we can merge this?
Thanks

**Comment by chrisrichardsevergreen** [comment]
> hi @chrisrichardsevergreen , Can you please fix your CLA so we can merge this? Thanks

Just waiting on a support ticket with EasyCLA - it's a corporate contribution.

**Review by blumamir — APPROVED** [review]

**Comment by blumamir** [comment]
Thanks, this is ready to be merged.
Can you please merge `main` into your branch once again? 
or select "Allow edits from maintainers" so we are able to do that

**Pull request merged**
