### PR TITLE
chore(deps): upgrade @types/pino to be compatible with latest sonic-stream types

### PR DESCRIPTION
**Pull request by legendecas**
## Which problem is this PR solving?

- #591 

## Short description of the changes

- upgrade @types/pino to 6.3.11

### CODE REVIEW

**Comment by Flarna** [comment]
Does this still work for users using an older version of @types/pino?

A while ago we had a discussion if we should pin the version here or not. Or even use `*` to accept any version selected in the final app.

**Review by Flarna — APPROVED** [review]

**Comment by legendecas** [comment]
> @Flarna Does this still work for users using an older version of @types/pino?

IIUC, types maintained in DefinitelyTyped versioned with the same `minor.patch` following the original package (see https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library). If there are no mistakes, the version of type packages should follow semantic versioning.

I'm not sure which condition you are referring to. If you mean users that declared their own @types/pino dependencies in their package, as long as the user-defined version is compatible with the version defined in @opentelemetry/instrumentation-pino, it should be fine.

**Comment by legendecas** [comment]
> Or even use * to accept any version selected in the final app.

IIUC, the instrumentation package should set a version range of pino that it supports (like say, declare a set of version range in peer dependencies). A `*` sounds not great to me.

**Comment by Flarna** [comment]
@types packages follow major.minor of their original. They may add/remove/rework definitions during this resulting in breakage like here. So in short @types packages don't follow semver (and this is documented at DefinitelyTyped).


> I'm not sure which condition you are referring to. If you mean users that declared their own @types/pino dependencies in their package, as long as the user-defined version range is compatible with the version defined in @opentelemetry/instrumentation-pino, it should be fine.

I mean the version selected by the end user. `@opentelemetry/instrumentation-pino` uses a fixed version therefore a mismatch is likely. In that case NPM installs both versions (one as child of `@opentelemetry/instrumentation-pino` and one in the root node_modules folder).

**Review by dyladan — APPROVED** [review]

**Comment by dyladan** [comment]
Merging this since it is fixing the build which breaks in every PR

**Pull request merged**
