### PR TITLE
Support OpenTelemetry SDK 0.8.x

### PR DESCRIPTION
**Pull request by dyladan**

### CODE REVIEW

**Comment by mayurkale22** [comment]
Would be nice if you can update examples too.

**Comment by justinwalz** [comment]
Hi all, a polite bump on this PR? I'm unable to use the latest otel releases as propagator jaeger is still pinned on context-base v0.6.x

```
Types have separate declarations of a private property '_currentContext'
```

Let me know if I can help out at all.

**Comment by dyladan** [comment]
I am going to update this today as we just actually released 0.8.1. It will be released probably tomorrow or wednesday. Is that ok?

**Comment by justinwalz** [comment]
That's perfect, no rush. Thank you!

**Comment by justinwalz** [comment]
Hey @dyladan I noticed 0.8.2 was released. Just wanted to ping a reminder here, just in case it got lost in the shuffle. Best, Justin

**Comment by dyladan** [comment]
Sorry @justinwalz I'll get to this tomorrow hopefully.

**Comment by dyladan** [comment]
@markwolff any idea why pg is failing again here?

**Pull request merged**
