### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@opentelemetry/auto-instrumentations-node: 0.27.3</summary>

### Bug Fixes

* **auto-instrumentations-node:** add more instrumentations ([#865](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/865)) ([6ba387a](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/6ba387ab45d0f67fdfac85c43bb0f0f67f2a119b))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-aws-lambda bumped from ^0.28.0 to ^0.29.0
    * @opentelemetry/instrumentation-express bumped from ^0.27.1 to ^0.28.0
    * @opentelemetry/instrumentation-generic-pool bumped from ^0.27.0 to ^0.27.2
    * @opentelemetry/instrumentation-graphql bumped from ^0.27.2 to ^0.27.3
    * @opentelemetry/instrumentation-nestjs-core bumped from ^0.28.1 to ^0.28.3
    * @opentelemetry/instrumentation-restify bumped from ^0.27.0 to ^0.27.2
</details>
<details><summary>@opentelemetry/browser-extension-autoinjection: 0.27.3</summary>

### Bug Fixes

* update eslint-plugin-import to resolve conflicts ([#864](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/864)) ([45efaee](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/45efaeec1da51398e44857dc9fe7ab3ef9456983))
</details>
<details><summary>@opentelemetry/instrumentation-aws-lambda: 0.29.0</summary>

### Features

* support using lambda context in the aws lambda context extractor ([#860](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/860)) ([5cb3266](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/5cb3266773f3f66d02af3306ae7332288bcae6af))
</details>
<details><summary>@opentelemetry/instrumentation-express: 0.28.0</summary>

### Features

* **express:** allow rewriting span names ([#463](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/463)) ([7510757](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/7510757aeeee47a7f0c4bb31de45be3a71bb673e))
</details>
<details><summary>@opentelemetry/instrumentation-generic-pool: 0.27.2</summary>

### Bug Fixes

* **auto-instrumentations-node:** add more instrumentations ([#865](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/865)) ([6ba387a](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/6ba387ab45d0f67fdfac85c43bb0f0f67f2a119b))
</details>
<details><summary>@opentelemetry/instrumentation-graphql: 0.27.3</summary>

### Bug Fixes

* **graphql:** move graphql to dependencies ([#850](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/850)) ([18e4f93](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/18e4f93007b19ecb33f8711ae0d20c51a90887d5))
</details>
<details><summary>@opentelemetry/instrumentation-nestjs-core: 0.28.3</summary>

### Bug Fixes

* **auto-instrumentations-node:** add more instrumentations ([#865](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/865)) ([6ba387a](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/6ba387ab45d0f67fdfac85c43bb0f0f67f2a119b))
</details>
<details><summary>@opentelemetry/instrumentation-restify: 0.27.2</summary>

### Bug Fixes

* **auto-instrumentations-node:** add more instrumentations ([#865](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/865)) ([6ba387a](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/6ba387ab45d0f67fdfac85c43bb0f0f67f2a119b))
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by blumamir — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/auto-instrumentations-node is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.27.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/browser-extension-autoinjection is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/browser-extension-autoinjection-v0.27.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-aws-lambda is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-lambda-v0.29.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-express is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-express-v0.28.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-generic-pool is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-generic-pool-v0.27.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-graphql is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.27.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-nestjs-core is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-nestjs-core-v0.28.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-restify is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-restify-v0.27.2 :sunflower:

**Pull request merged**
