### PR TITLE
fix(amqplib): use extracted context for message consuming

### LINKED ISSUE #1351: amqplib looses Baggage
### What version of OpenTelemetry are you using?
amqplib: 0.32.0

### What version of Node are you using?
19.4.0

### What did you do?
I'm using baggage propagators and I realized that I loose the baggage when I consume messages.

### What did you expect to see?
`propagator.getBaggage(context.active())` should return the baggage of the amqp header

### What did you see instead?
I get null/empty

### Additional context
I already found the problem: the wrong context is passed into the `setSpan` method.

image

Right now, the `context.active()` is passed in, but actually the `parentContext` must be passed in since only this one contains the baggage.

### PR DESCRIPTION
**Pull request by nerumo**
fixes #1351 baggage propagation

## Which problem is this PR solving?
the baggage is lost while consuming messages since the extracted context isn't passed in

## Short description of the changes
we pass in the extracted context to the `context.with(....)`

### CODE REVIEW

**Comment by blumamir** [comment]
Thanks for the fix. Can you please add a test for that?

**Comment by nerumo** [comment]
> Thanks for the fix. Can you please add a test for that?

I can't make the repository work on my machine (node-gyp native build problems). The scoped bootstrap is also failing. It's taking too much time for me, I can't continue here :( 

I pushed the untested/incomplete test

**Comment by nerumo** [comment]
so, got it running in WSL. and funny, the test I wrote worked on the first try 🎉

**Review by blumamir — COMMENTED** [review]
Thanks!
Can you please fix the linting?

**Comment by Flarna** [comment]
```
/__w/opentelemetry-js-contrib/opentelemetry-js-contrib/plugins/node/instrumentation-amqplib/test/amqplib-callbacks.test.ts
   17:9   error  Replace `expect` with `·expect·`                                                                                                                                                                       prettier/prettier
   18:9   error  Replace `AmqplibInstrumentation` with `·AmqplibInstrumentation·`                                                                                                                                       prettier/prettier
   31:9   error  Replace `Baggage,·context,·propagation,·SpanKind` with `·Baggage,·context,·propagation,·SpanKind·`                                                                                                     prettier/prettier
   32:9   error  Replace `asyncConfirmSend,·asyncConsume,·shouldTest` with `·asyncConfirmSend,·asyncConsume,·shouldTest·`                                                                                               prettier/prettier
   39:9   error  Replace `CompositePropagator,·W3CBaggagePropagator,·W3CTraceContextPropagator` with `⏎··CompositePropagator,⏎··W3CBaggagePropagator,⏎··W3CTraceContextPropagator,⏎`                                    prettier/prettier
   47:37  error  Insert `⏎······`                                                                                                                                                                                       prettier/prettier
   48:7   error  Replace `propagators:·[new·W3CBaggagePropagator(),·new·W3CTraceContextPropagator()` with `··propagators:·[⏎··········new·W3CBaggagePropagator(),⏎··········new·W3CTraceContextPropagator(),⏎········`  prettier/prettier
   49:1   error  Replace `····})` with `······})⏎····`                                                                                                                                                                  prettier/prettier
   77:38  error  Delete `⏎··········`                                                                                                                                                                                   prettier/prettier
   81:14  error  Replace `durable:·false` with `·durable:·false·`                                                                                                                                                       prettier/prettier
  100:16  error  Delete `⏎······`                                                                                                                                                                                       prettier/prettier
  135:1   error  Delete `··`                                                                                                                                                                                            prettier/prettier
  167:11  error  Delete `··`                                                                                                                                                                                            prettier/prettier
  198:53  error  Replace `context.active(),` with `⏎········context.active(),⏎·······`                                                                                                                                  prettier/prettier
  199:9   error  Replace `key1:·{value:·'value1'` with `··key1:·{·value:·'value1'·`                                                                                                                                     prettier/prettier
  200:7   error  Replace `})` with `··})⏎······`                                                                                                                                                                        prettier/prettier
  202:29  error  Replace `⏎··········queueName,⏎··········Buffer.from(msgPayload)⏎········` with `queueName,·Buffer.from(msgPayload)`                                                                                   prettier/prettier
  210:12  error  Insert `⏎············`                                                                                                                                                                                 prettier/prettier
  211:1   error  Insert `··`                                                                                                                                                                                            prettier/prettier
  212:11  error  Replace `}` with `··},⏎··········`                                                                                                                                                                     prettier/prettier
  256:45  error  Delete `⏎··········`                                                                                                                                                                                   prettier/prettier
  260:14  error  Replace `durable:·false` with `·durable:·false·`                                                                                                                                                       prettier/prettier
  279:16  error  Delete `⏎······`                                                                                                                                                                                       prettier/prettier
  306:13  error  Delete `··`                                                                                                                                                                                            prettier/prettier
  311:1   error  Delete `··`                                                                                                                                                                                            prettier/prettier
  319:1   error  Delete `··`                                                                                                                                                                                            prettier/prettier
  342:13  error  Delete `··`                                                                                                                                                                                            prettier/prettier
  347:1   error  Delete `··`                                                                                                                                                                                            prettier/prettier
  355:1   error  Delete `··`                                                                                                                                                                                            prettier/prettier
```
it's in amqplib tests

**Comment by nerumo** [comment]
ah, I see. I fixed it, thank you for the other changes.

**Comment by Flarna** [comment]
CI fails for node 18. Not sure why nor if it is caused by this PR as CI logs don't show any useful hint.

**Review by blumamir — APPROVED** [review]

**Pull request merged**
