### PR TITLE
style: use single quotes everywhere and add a rule to eslint

### PR DESCRIPTION
**Pull request by CptSchnitz**
## Which problem is this PR solving?

- #582 

## Short description of the changes

- Added ESlint rule for single quote
- Ran ESlint:fix on the entire repo
- Went over the README's and changed to single quotes there
- fixed single quotes in scripts

(There's also eslint.config.js itself, but I wasn't sure if everywhere includes it, tell me if I should also edit it)

### CODE REVIEW

**Comment by CptSchnitz** [comment]
So it failed the test because of a package that came out a few minutes ago (@babel/parser):
image

that's interesting 😅

**Comment by Rauno56** [comment]
It's probably just bad timing. `@babel/core` was published, the dependency was not.
Trigger new CI run with an empty commit `git commit --allow-empty`.

**Comment by vmarchaud** [comment]
i've restarted the build myself but you should be able to do it if you go on the build page (by clicking on either tasks) and click on "Restart all jobs" on something like this at the top right

**Comment by CptSchnitz** [comment]
When i look at my own repos, i have a button that says "re-run jobs",
but it doesn't show up here.

**Review by blumamir — APPROVED** [review]

**Review by Rauno56 — APPROVED** [review]

**Review by vmarchaud — APPROVED** [review]

**Review by obecny — APPROVED** [review]

**Pull request merged**
