### PR TITLE
chore: metrics collector - proposition - ON HOLD

### PR DESCRIPTION
**Pull request by obecny**
## Which problem is this PR solving?

- Based on 
https://github.com/open-telemetry/opentelemetry-js/issues/623
and 
https://github.com/open-telemetry/opentelemetry-js/issues/955

## Short description of the changes

- Adds package to collect Metrics

FYI
Compiling packages works fine locally, compiling on circleCI and then installing from there is not yet done / wip

This is a proposition, naming conventions can be changed easily.

### CODE REVIEW

**Comment by obecny** [comment]
@mwear ^^

**Comment by dyladan** [comment]
"collector" name is potentially confusing with the opentelemetry collector

**Comment by obecny** [comment]
I'm keeping this on hold, as it needs anyway refactoring due to changes in metrics which are still either in review or waits for those in review and then few new to be implemented

**Comment by obecny** [comment]
refactored in new PR

**Pull request closed without merging**
