### PR TITLE
fix: install @types/form-data

### PR DESCRIPTION
**Pull request by Rauno56**
## Which problem is this PR solving?

I honestly do not know what exactly caused the issue in the first place, because the first commit that had the issue on the `main` didn't have any code changes and I'm not able to repro that locally, but simply following the instructions `tsc` suggested seems to make the compiler chill.

## Short description of the changes

Installed `@types/form-data` in the root.
Created https://github.com/open-telemetry/opentelemetry-js-contrib/issues/901 to remove it later.

## Checklist

- [ ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.

### CODE REVIEW

**Comment by Flarna** [comment]
Most likely caused because `@types/node-fetch` version 2.6.0 was published which depends on `form-data` ^2.3.3 whereas the previous version 2.5.12 depended on `form-data` ^3.0.0.

I don't have this problem local therefore I assume some ci caching is additionally needed.

**Comment by Rauno56** [comment]
> Most likely caused because @types/node-fetch version 2.6.0 was published which depends on form-data ^2.3.3 whereas the previous version 2.5.12 depended on form-data ^3.0.0.

I'm aware of that, but the confusing part is the fact that node-fetch is a dep of lerna and codecov - I wonder why does that affect our compilations.

**Comment by Flarna** [comment]
there is also following in instrumentation tedious: tedious@14.1.0 => @azure/identity@1.5.2 => @azure/keyvault-keys@4.3.0 => @azure/core-http@2.2.4 => node-fetch@2.6.7 and @types/node-fetch@2.6.0

and the lerna hosting seems to move around/dedup stuff a bit.

**Comment by Rauno56** [comment]
Thanks, @Flarna for your help bouncing this! I removed `codecov` instead of going with this hack for now. Removing it was due anyway because it has been deprecated for a while now.

**Comment by Flarna** [comment]
welcome! I guess once it's done here we should do the same in opentelemetry-js and opentelemetry-js-api repos.

**Pull request closed without merging**
