### PR TITLE
chore(deps): update deps @opentelemetry/semantic-conventions to 1.27

### PR DESCRIPTION
**Pull request by maryliag**
Update `@opentelemetry/semantic-conventions` to 1.27

### CODE REVIEW

**Comment by pichlermarc** [comment]
@maryliag, I'm sorry, I introduced a lot of conflicts by merging #2408 :(
 Would you mind updating again? The package-lock diff should be much smaller then too as the dependency has already been pulled in in #2408

**Comment by maryliag** [comment]
@pichlermarc no need to apologize :) 
updated the branch with latest from main

**Comment by maryliag** [comment]
@pichlermarc after the merge with main, it actually added quite a few changes to the package-lock file....

**Comment by pichlermarc** [comment]
> @pichlermarc after the merge with main, it actually added quite a few changes to the package-lock file....

@maryliag, ah that looks like it was an `npm install` instead of an `npm install --package-lock-only` that completely re-wrote the `package-lock.json`. I pushed another commit [8c997c5](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2409/commits/8c997c56ed535070138cec1e34f7a6d7a3f3ce00) where I reset the `package-lock.json` to the one from `main` and did an `npm install --package-lock-only` and now the diff just syncs the `package.json` files in. :slightly_smiling_face:

**Review by pichlermarc — APPROVED** [review]

**Pull request merged**
