### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>@opentelemetry/auto-instrumentations-node: 0.40.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-amqplib bumped from ^0.33.3 to ^0.33.4
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.36.2 to ^0.37.0
    * @opentelemetry/instrumentation-cassandra-driver bumped from ^0.34.0 to ^0.34.1
    * @opentelemetry/instrumentation-ioredis bumped from ^0.35.3 to ^0.36.0
    * @opentelemetry/instrumentation-lru-memoizer bumped from ^0.33.3 to ^0.33.4
    * @opentelemetry/instrumentation-memcached bumped from ^0.32.3 to ^0.32.4
    * @opentelemetry/instrumentation-mongodb bumped from ^0.37.2 to ^0.37.3
    * @opentelemetry/instrumentation-mongoose bumped from ^0.33.3 to ^0.33.4
    * @opentelemetry/instrumentation-mysql bumped from ^0.34.3 to ^0.34.4
    * @opentelemetry/instrumentation-mysql2 bumped from ^0.34.3 to ^0.34.4
    * @opentelemetry/instrumentation-pg bumped from ^0.37.0 to ^0.37.1
    * @opentelemetry/instrumentation-redis bumped from ^0.35.3 to ^0.35.4
    * @opentelemetry/instrumentation-redis-4 bumped from ^0.35.4 to ^0.35.5
    * @opentelemetry/instrumentation-socket.io bumped from ^0.34.3 to ^0.34.4
    * @opentelemetry/instrumentation-tedious bumped from ^0.6.3 to ^0.6.4
    * @opentelemetry/resource-detector-alibaba-cloud bumped from ^0.28.3 to ^0.28.4
    * @opentelemetry/resource-detector-aws bumped from ^1.3.3 to ^1.3.4
    * @opentelemetry/resource-detector-container bumped from ^0.3.3 to ^0.3.4
    * @opentelemetry/resource-detector-gcp bumped from ^0.29.3 to ^0.29.4
</details>

<details><summary>contrib-test-utils: 0.35.0</summary>

### Features

* **test-utils:** runTestFixture utility for running out-of-process tests ([#1735](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1735)) ([4c8b374](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/4c8b37453225769ec5f7b3c97a2bf0de673bc60f))
</details>

<details><summary>@opentelemetry/instrumentation-amqplib: 0.33.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>instrumentation-aws-sdk: 0.37.0</summary>

### ⚠ BREAKING CHANGES

* **instrumentation-aws-sdk:** Capture full ARN for span attribute messaging.destination.name for SNS topics ([#1727](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1727))

### Features

* **instrumentation-aws-sdk:** Capture full ARN for span attribute messaging.destination.name for SNS topics ([#1727](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1727)) ([28ea3b6](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/28ea3b6d9d4ddb3b6d635a7d7b26b0721cf448db))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/propagation-utils bumped from ^0.30.3 to ^0.30.4
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-cassandra-driver: 0.34.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>instrumentation-ioredis: 0.36.0</summary>

### Features

* **test-utils:** runTestFixture utility for running out-of-process tests ([#1735](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1735)) ([4c8b374](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/4c8b37453225769ec5f7b3c97a2bf0de673bc60f))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-lru-memoizer: 0.33.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-memcached: 0.32.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-mongodb: 0.37.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-mongoose: 0.33.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-mysql: 0.34.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-mysql2: 0.34.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-pg: 0.37.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-redis: 0.35.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-redis-4: 0.35.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-socket.io: 0.34.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-tedious: 0.6.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/propagation-utils: 0.30.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/resource-detector-alibaba-cloud: 0.28.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/resource-detector-aws: 1.3.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>resource-detector-azure: 0.2.1</summary>

### Bug Fixes

* Export All Azure Resource Detectors ([#1800](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1800)) ([7370386](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/7370386f2ea0d156434a127aac4e90af67b9457b))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/resource-detector-container: 0.3.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/resource-detector-gcp: 0.29.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

<details><summary>@opentelemetry/resource-detector-instana: 0.5.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @opentelemetry/contrib-test-utils bumped from ^0.34.3 to ^0.35.0
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by pichlermarc** [comment]
Looks like release-please is not updating the package-lock.json which makes CI fail in release PRs

**Comment by pichlermarc** [comment]
Looking at the diff it seems that a part of the problem here is that the xray sampler is not updated by release please (it's a private unreleased package) and then it's trying to pull in 0.34.3 of the test-utils, but only 0.35.0 is available locally.

For now, before releasing (happens by merging this PR) we'll need to run `npm install --package-lock-only`, commit, push to the release PR's branch and then merge.

**Review by pichlermarc — APPROVED** [review]
Problems are fixed by #1817
Good to release now.

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-alibaba-cloud-v0.28.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-aws-v1.3.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-azure-v0.2.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-container-v0.3.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-gcp-v0.29.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/resource-detector-instana-v0.5.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.40.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/propagation-utils-v0.30.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/contrib-test-utils-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-amqplib-v0.33.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-lru-memoizer-v0.33.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongoose-v0.33.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-socket.io-v0.34.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-tedious-v0.6.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.37.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-ioredis-v0.36.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-memcached-v0.32.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongodb-v0.37.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mysql-v0.34.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mysql2-v0.34.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pg-v0.37.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-v0.35.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-4-v0.35.5 :sunflower:

**Pull request merged**
