### PR TITLE
docs(graphql-instrumentation): add documentation for ignoreResolveSpans

### PR DESCRIPTION
**Pull request by satazor**
## Which problem is this PR solving?

- Adds missing documentation for ignoreResolveSpans options to graphql instrumentation

## Short description of the changes

- Updated readme

### CODE REVIEW

**Review by diogotorres97 — APPROVED** [review]

**Comment by trentm** [comment]
For reference the `ignoreResolveSpans` option was added in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1858

**Comment by trentm** [comment]
Thanks for following up on https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1858 with this PR!

**Comment by satazor** [comment]
@trentm suggestions accepted

**Review by trentm — APPROVED** [review]

**Comment by trentm** [comment]
@seemk You implemented https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1858. Would you like to review this before it is merged? Thanks.

**Review by seemk — APPROVED** [review]

**Pull request merged**
