### PR TITLE
fix(aws-sdk): add http status code attribute to aws sdk span if aws sdk v3 client exception occurs

### PR DESCRIPTION
**Pull request by jj22ee**
## Which problem is this PR solving?

Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2343

- Upon AWS SDK (v3) Client exceptions, AWS SDK V3 Span will not record http.status.code attribute into the span.
  - For comparison, AWS SDK V2 Span already does record and [expects this attribute](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v2.test.ts#L301-L303).

## Short description of the changes

- Record `http.status.code` attribute into the span upon client exceptions for AWS SDK V3 Spans.

## Testing

- Updated Unit Tests to check for `http.status.code` attribute

### CODE REVIEW

**Review by maryliag — APPROVED** [review]

**Review by vastin — APPROVED** [review]
LGTM

**Comment by jj22ee** [comment]
Pinging @blumamir for approval and merge.

**Review by blumamir — APPROVED** [review]

**Comment by blumamir** [comment]
Thanks you @jj22ee for the contribution.
Please fix the linting so I can merge.

```sh
npm run lint:fix
```

**Comment by jj22ee** [comment]
@blumamir done!

**Pull request merged**
