### PR TITLE
chore(deps): Updated zone.js version to support latest Angular

### PR DESCRIPTION
**Pull request by AndrewAKovalenko**
## Which problem is this PR solving?

- Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1820

## Short description of the changes

- Update Zone.js version to support Angular 17

### CODE REVIEW

**Comment by AndrewAKovalenko** [comment]
@pichlermarc signed CLA, now everything should be ready to merge :)

I see that [PR to core library](https://github.com/open-telemetry/opentelemetry-js/pull/4469 ) is merged, so, please, merge this one whenever core library is released

Thanks in advance!

**Comment by sgrigsoftserve** [comment]
Any updates on this issue ?

**Comment by HenryCorn** [comment]
Hi all. Is there an estimate day for this to be released?

**Comment by sgrigsoftserve** [comment]
This is a real blocker for a lot of teams, can this not be prioritized somehow?

**Comment by angeloimm** [comment]
Any update on this? It's blocking to our teams too; it would very appreciated if this PR would be accepted

**Comment by keastm** [comment]
Hey Guys, 
I just come across this as a Blocker.. can we get this merged asap?

**Comment by pichlermarc** [comment]
We need to get the core release out first. I get that it's a blocker for you, but I can't give you a proper estimation right now (we have some tooling issues right now so it can be rather quick, or it can take a week).

I have not forgotten about this PR and will merge it when we've released core and updated the repo.

**Review by pichlermarc — APPROVED** [review]

**Pull request merged**
