### PR TITLE
chore: add component owners to redis and ioredis

### PR DESCRIPTION
**Pull request by blumamir**
I would like to suggest myself as component owner for the `ioredis` and `redis` instrumentations.
Been using them for quite some time, and also created a few PRs with fixes in the past.

Not sure who originally wrote them. Happy to share ownership with whoever wants to join, or close this PR if the ownership should be set on someone else.

### CODE REVIEW

**Comment by vmarchaud** [comment]
I believe @Flarna wrote the ioredis instrumentation based on the old plugin wrote by @naseemkullah (https://github.com/open-telemetry/opentelemetry-js/pull/558).
Redis one was written by @markwolff but he's not active anymore so i don't think its a problem

**Review by vmarchaud — APPROVED** [review]

**Review by MSNev — APPROVED** [review]

**Comment by naseemkullah** [comment]
> I believe @Flarna wrote the ioredis instrumentation based on the old plugin wrote by @naseemkullah ([open-telemetry/opentelemetry-js#558](https://github.com/open-telemetry/opentelemetry-js/pull/558)).
> Redis one was written by @markwolff but he's not active anymore so i don't think its a problem

Ah, memories :)

Feel free to add me for ioredis @blumamir

**Review by naseemkullah — APPROVED** [review]

**Review by dyladan — APPROVED** [review]

**Comment by dyladan** [comment]
Will wait on @blumamir's response about ioredis ownership but this can merge as soon as that happens.

**Comment by blumamir** [comment]
> > I believe @Flarna wrote the ioredis instrumentation based on the old plugin wrote by @naseemkullah ([open-telemetry/opentelemetry-js#558](https://github.com/open-telemetry/opentelemetry-js/pull/558)).
> > Redis one was written by @markwolff but he's not active anymore so i don't think its a problem
> 
> Ah, memories :)
> 
> Feel free to add me for ioredis @blumamir

Sure, added 👍

**Comment by naseemkullah** [comment]
Thanks @blumamir!

**Pull request merged**
