### PR TITLE
chore(GHA): Update the usage of set-output command in GH actions

### PR DESCRIPTION
**Pull request by vasireddy99**
This PR updates the usage of set-output command in GH actions.

Reference : https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ChangeLog entry is not required

### CODE REVIEW

**Comment by blumamir** [comment]
Thanks
Seems CI now fails when running this job.
Can you please take a look?

**Comment by vasireddy99** [comment]
> Thanks
> Seems CI now fails when running this job.
> Can you please take a look?

yes for sure, i would take a look for any failures in running this job, but couldn't find any error related to this in workflows. please redirect me to the failure if you get a chance. other than that this particular change in this pr would work fine 🙂.

**Comment by vasireddy99** [comment]
> Thanks
> Seems CI now fails when running this job.
> Can you please take a look?

yes for sure, fixed the PR build should be good for review 🙂

**Review by blumamir — APPROVED** [review]
Thanks! 💯

**Comment by blumamir** [comment]
Please rebase this branch so I can merge, or ["allow edits from maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so we can rebase and merge on one go

**Review by pichlermarc — APPROVED** [review]

**Pull request merged**
