### PR TITLE
Update ioredis library from 4.27.7 to 5.0.6

### PR DESCRIPTION
**Pull request by raushi**
## Which problem is this PR solving?
- It is not working with ioredis 5.0+ version. It will fix that

## Short description of the changes
- Update ioredis version from 4.27.7 to 5.0.6 

## Checklist

- [ ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.

### CODE REVIEW

**Comment by Rauno56** [comment]
At minimum we should also add test-all-versions configuration to also test 5.x range.
The file I'm talking about is `.tav.yml`. For now, just addig `^5 || ...` to the range is probably enough.

**Comment by dyladan** [comment]
If the instrumentation doesn't work with 5.x then simply updating the devdependency is unlikely to fix the real issue

**Comment by Rauno56** [comment]
Right. @raushi , would you like to work on adding the support for v5 of `ioredis`?

**Comment by raushi** [comment]
> Right. @raushi , would you like to work on adding the support for v5 of `ioredis`?

Yes.

**Comment by blumamir** [comment]
To add support for `ioredis` for version 5, you should begin with updating the supportedVersions [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/e2657232c9007a77ddc873a93e8247f99087b9c1/plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts#L52).

Instrumentation code will probably also need to update to support the new moduleExports. Relevant issue: #978

**Pull request closed without merging**
