### PR TITLE
feat(auto-instrumentations-node): enable auto-instrumentation for KafkaJS

### LINKED ISSUE #1554: Request to add kafkajs instrumentation (opentelemetry-instrumentation-kafkajs) module to OpenTelemetry Meta Packages for Node (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#supported-instrumentations).
This is not a new instrumentation request. The instrumentation already exists. The request is to add kafkajs instrumentation (opentelemetry-instrumentation-kafkajs) module to OpenTelemetry Meta Packages for Node (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#supported-instrumentations).

### Is your instrumentation request related to a problem? Please describe
A lot of users use kafkajs with node.js application in K8s and do not want to modify their source code or their application image with a tracing.js while instrumenting it with OpenTelemetry. The OpenTelemetry operator provides a way to achieve that. However it can instrument only the supported node.js packages mentioned at https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#supported-instrumentations.

As kafkajs is not included in the above list, there is no way to instrument kafka calls made by node.js using kafkajs framework. The only way to instrument such kafka call is to add a tracing.js into the application image and not use Opentelemetry operator to inject instrumentation. However, most of the times, it is a bit cumbersome.

### Is it applicable for Node or Browser or both?
Only Node.

### Do you expect this instrumentation to be commonly used?
Weekly Downloads:

### What version of instrumentation are you interested in using?
Versions:

### LINKED ISSUE #1845: Can we please add the opentelemetry-instrumentation-kafkajs (https://www.npmjs.com/package/opentelemetry-instrumentation-kafkajs) to nod.js auto-instrumention, please?
### Is your instrumentation request related to a problem? Please describe
It is not related to a problem, just to address inconvenience while doing Node.js auto injection and auto-instrumentation via OpenTelemetry operator in k8s. As opentelemetry-instrumentation-kafkajs is not included in the auto-instrumentation library, the kafka calls cannot be instrumented while using k8s opentelemetry operator and the instrumentation has to be manually injected using a tracing.js file.

### Is it applicable for Node or Browser or both?
It is mostly for node.

### Do you expect this instrumentation to be commonly used?
Yes, a lot.

### What version of instrumentation are you interested in using?
Versions: 0.40.0

### PR DESCRIPTION
**Pull request by brianphillips**
## Which problem is this PR solving?

- Fixes #1845 and Fixes #1554 

## Short description of the changes

- This PR adds `@opentelemetry/instrumentation-kafkajs` to the `@opentelemetry/auto-instrumentations-node` meta package

### CODE REVIEW

**Comment by trentm** [comment]
@brianphillips Are you able to sign the CLA? See the comment above this one.

**Comment by trentm** [comment]
Note that the intent when adding instrumentation-kafkajs a number of weeks ago was to eventually add it to auto-instruemtnations-node: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2089#issuecomment-2092398396

**Comment by brianphillips** [comment]
@trentm I'm waiting on our corporate legal counsel to figure out how to sign the CCLA. I'll check in again (they tried earlier this week and weren't able to gain access and opened a ticket? I'm not really sure...)

**Comment by brianphillips** [comment]
@trentm ok, we should be good to go

**Pull request merged**
