### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>auto-instrumentations-node: 0.33.0</summary>

### Features

* add dataloader instrumentation ([#1171](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1171)) ([3898b11](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/3898b11800f857c75c286f22c4633b5baf4e1f84))
* add mongoose instrumentation ([#1131](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1131)) ([b35277b](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/b35277bb5fc66910e8942bc0b64347b68ecffa26))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.9.1 to ^0.9.2
    * @opentelemetry/instrumentation-dataloader bumped from ^0.1.0 to ^0.2.0
    * @opentelemetry/instrumentation-fastify bumped from ^0.29.0 to ^0.30.0
    * @opentelemetry/instrumentation-mongodb bumped from ^0.32.0 to ^0.32.1
    * @opentelemetry/instrumentation-mongoose bumped from ^0.30.0 to ^0.31.0
</details>

<details><summary>host-metrics: 0.30.1</summary>

### Bug Fixes

* readme snippet ([#1182](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1182)) ([35d1e45](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/35d1e4579f7b160c501959f6fb45859b75cdde99))
</details>

<details><summary>instrumentation-aws-sdk: 0.9.2</summary>

### Bug Fixes

* **aws-sdk:** set spanKind to CLIENT by default in v3 ([#1177](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1177)) ([d463695](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/d463695f5258875f1da0c7b17c20f7df93494d4e))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/propagation-utils bumped from ^0.28.0 to ^0.29.0
</details>

<details><summary>instrumentation-dataloader: 0.2.0</summary>

### Features

* add dataloader instrumentation ([#1171](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1171)) ([3898b11](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/3898b11800f857c75c286f22c4633b5baf4e1f84))
* upstream mocha instrumentation testing plugin from ext-js [#621](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/621) ([#669](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/669)) ([a5170c4](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a5170c494706a2bec3ba51e59966d0ca8a41d00e))
</details>

<details><summary>instrumentation-fastify: 0.30.0</summary>

### Features

* **opentelemetry-instrumentation-fastify:** Support Fastify V4 also ([#1164](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1164)) ([d932d3e](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/d932d3edcbf41685ca0af546347450fa81444b4e))
</details>

<details><summary>instrumentation-mongodb: 0.32.1</summary>

### Bug Fixes

* remove unneeded type exports in mongodb instrumentation ([#1194](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1194)) ([6920a55](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/6920a554b46bf8af5e00b60073d479feacb18dcd))
</details>

<details><summary>instrumentation-mongoose: 0.31.0</summary>

### Features

* add mongoose instrumentation ([#1131](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1131)) ([b35277b](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/b35277bb5fc66910e8942bc0b64347b68ecffa26))
* upstream mocha instrumentation testing plugin from ext-js [#621](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/621) ([#669](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/669)) ([a5170c4](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a5170c494706a2bec3ba51e59966d0ca8a41d00e))
</details>

<details><summary>propagation-utils: 0.29.0</summary>

### Features

* **propagation-utils:** end pub-sub process span on promise settled ([#1055](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1055)) ([cb83d30](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/cb83d300582b4d485be56563634cd3859069004c))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by Rauno56 — CHANGES_REQUESTED** [review]
Merge https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1202 first.

**Review by Rauno56 — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.33.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/host-metrics-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/propagation-utils-v0.29.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongoose-v0.31.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-dataloader-v0.2.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.9.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fastify-v0.30.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-mongodb-v0.32.1 :sunflower:

**Comment by Flarna** [comment]
seems nothing was published to NPM once again. Did the release please job ever succeed on a release here?

**Pull request merged**
