### PR TITLE
fix: hapi compilation

### PR DESCRIPTION
**Pull request by Flarna**
## Short description of the changes

Fix compilation issues by pinning @hapi/podium to 4.1.1 as later version has it's own typings which is not compatible with remaining dependencies.

### CODE REVIEW

**Comment by dyladan** [comment]
Once you get past the hapi stage you will need to apply https://github.com/open-telemetry/opentelemetry-js-contrib/pull/406/commits/a3f5b0d50516c8c3acc977b575dc4287eef0b6d2 too probably

**Comment by Flarna** [comment]
An alternative to this change would be most likely that one described in hapi issue tracker: https://github.com/hapijs/hapi/issues/4240#issuecomment-810860745

**Comment by Flarna** [comment]
> Once you get past the hapi stage you will need to apply [a3f5b0d](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a3f5b0d50516c8c3acc977b575dc4287eef0b6d2) too probably

I cherry-picked this change. But honestly speaking I'm not a big fan of this. I think we should move to 0.18.2 everywhere instead at a few locations only.

**Comment by dyladan** [comment]
> > Once you get past the hapi stage you will need to apply [a3f5b0d](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/a3f5b0d50516c8c3acc977b575dc4287eef0b6d2) too probably
> 
> I cherry-picked this change. But honestly speaking I'm not a big fan of this. I think we should move to 0.18.2 everywhere instead at a few locations only.

I agree, but this is the minimum to fix the currently broken compile and it is a dev dependency only

**Review by dyladan — APPROVED** [review]

**Review by obecny — APPROVED** [review]

**Pull request merged**
