### PR TITLE
fix: Removed deprecated properties usage in Fastify instrumentation

### PR DESCRIPTION
**Pull request by seidelmartin**
## Which problem is this PR solving?

Instrumentation has been using deprecated properties producing errors like `FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in fastify@5.`
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1275

## Short description of the changes

I've added getting deprecated properties from newly introduced `routeOptions` object in fastify request. It supports also old versions that doesn't have this object exposed. It has been introduced in fastify https://github.com/fastify/fastify/releases/tag/v4.23.0

### CODE REVIEW

**Comment by seidelmartin** [comment]
Hi @pichlermarc. I'm confused by the GH workflow failure. Is it something that fails globally or just in my PR? I've tried `main` version locally and `lerna boostrap` fails for me as well...

**Comment by pichlermarc** [comment]
@seidelmartin I'm looking into it, I think it may be both. Trying it on this branch makes it fail on the fastify intrumentation's `prepare` script, but trying it on `main` makes it fail for the AWS SDK instrumentation for me. :thinking: I'm not sure yet what the cause for it is, yet; I'll keep you posted.

**Comment by pichlermarc** [comment]
@seidelmartin looks like I had an old revision checked out and `main` is actually compiling fine when re-installing dependencies. I think the problem here could be that the types from `@types/mongodb` hoisted to the project root no longer compile with typescript 5 (we align typescript for this reason). Would you mind trying with the lowest possible typescript version that still compiles with fastify? :thinking: Otherwise we'll have to add `--nohoist='@types/mongodb'` when running `lerna bootstrap`.

**Comment by seidelmartin** [comment]
@pichlermarc I'll try that. 👍🏻

**Comment by seidelmartin** [comment]
@pichlermarc good news, after downgrading typescript to 4.7.4 all checks pass.

**Comment by seidelmartin** [comment]
Alright, all 🟢.

**Comment by seidelmartin** [comment]
Hi @pichlermarc, what will be the next step here to publish it as new version?

**Review by pichlermarc — COMMENTED** [review]
Looks good, thanks @seidelmartin :slightly_smiling_face: 
Once this is merged, a release PR is created automatically. 

@blumamir do we have any specific limitations on bumping typescript for a single package in this repo? :thinking: Since this package is not 1.0 yet, we can make a breaking change like bumping it for `@opentelemetry/instrumentation-fastify` (it's needed for new versions of the package anyway). Thinking about it closer though, it'll likely affect `@opentelemetry/auto-instrumentations-node` too by possibly requiring a later version for consumers.

**Comment by blumamir** [comment]
> Looks good, thanks @seidelmartin 🙂 Once this is merged, a release PR is created automatically.
> 
> @blumamir do we have any specific limitations on bumping typescript for a single package in this repo? 🤔 Since this package is not 1.0 yet, we can make a breaking change like bumping it for `@opentelemetry/instrumentation-fastify` (it's needed for new versions of the package anyway). Thinking about it closer though, it'll likely affect `@opentelemetry/auto-instrumentations-node` too by possibly requiring a later version for consumers.

To my latest understanding, if we use a newer typescript, we can break existing users with incompatible versions. But @Flarna will probably know best

**Comment by Flarna** [comment]
Newer typescript versions may generated .d.ts files which are incompatible with an older typescript version.
I don't have in mind which ts version includes such problematic changes but it's not bound to major versions only. I guess a search in the issue tracker of [core repo](https://github.com/open-telemetry/opentelemetry-js) has more details.

While typescript brings a lot of benefits it adds also some compatibility burden...

An update of typescript will for sure happen with SDK 2.0.

**Comment by blumamir** [comment]
Why do we need to bump the typescript version in the first place? is it so we can use `"fastify": "4.23.0"` instead of `4.18.0` to verify the tests assert this fix?

Perhaps we can keep all current dependencies as they are and use `test-all-versions` script to cover all versions instrumentation supports?

**Comment by seidelmartin** [comment]
> Why do we need to bump the typescript version in the first place? is it so we can use `"fastify": "4.23.0"` instead of `4.18.0` to verify the tests assert this fix?
> 
> Perhaps we can keep all current dependencies as they are and use `test-all-versions` script to cover all versions instrumentation supports?

I've updated fastify to v4.23.0 because it exposes new properties that instrumentation uses. Otherwise it still produces a lot of deprecation warnings. I can still downgrade it but then I wouldn't be able to test my changes.

**Comment by Fernandomr88** [comment]
Guys, this is generating tons of errors in production, what's the ETA of this PR?

**Comment by pichlermarc** [comment]
Thanks to everyone for the feedback on the PR here. 

I've created a PR to add a `test-all-versions` script that will allow us to keep `fastify@4.18.0`/`typescript@4.4.4`, while at the same time also allowing us to test against `fastify@4.23.2`/`typescript@4.7.4` (#1710). This way we won't run into compatibility issues with users of `typescript@4.4.4`.

@seidelmartin would you mind changing the dependencies back to `fastify@4.18.0`/`typescript@4.4.4`? Once #1710 is merged we'll then automatically test against  `fastify@4.23.2` when the `pkg:instrumentation-fastify` label is applied - and once that passes we can merge this PR. :slightly_smiling_face:

**Comment by seidelmartin** [comment]
Yes, I'll do that.

**Comment by markrzen** [comment]
@seidelmartin You may want to rebase to main as it appears you are out-of-date.

**Comment by seidelmartin** [comment]
@markrzen I've rebased to latest version. Can we proceed with it? What will be next steps?

**Comment by markrzen** [comment]
@seidelmartin I don't have access to approve, I am just another contributor like yourself.

@pichlermarc Anything else to get this PR approved?

**Comment by markrzen** [comment]
@open-telemetry/javascript-approvers Anyone able to review this PR? It's a fairly simple update, impactful and getting long in the tooth.

**Comment by Fernandomr88** [comment]
awesome! When will this be available @ Npm?

**Comment by pichlermarc** [comment]
@Fernandomr88 we released it earlier today: https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fastify-v0.32.3

**Pull request merged**
