### PR TITLE
test: test with Node.js 22

### PR DESCRIPTION
**Pull request by trentm**
It is long past time to be testing with Node.js 22.
The core repo is already doing so (as of https://github.com/open-telemetry/opentelemetry-js/pull/4666).

### CODE REVIEW

**Comment by trentm** [comment]
1. I think there is a flaky test in socket.io.test.ts with (a) the socket.io package version in package.json and Node.js 18, 20, and 22 (at least). I think I have a workaround for that, with a theory at the issue, but not a full smoking gun.

2. The test-all-versions CI run failed in socket.io.test.ts when testing against socket.io@2, actually against the latest 2.x: version 2.5.1.   2.5.1 was recently released, even though 2.x releases hadn't happened for a long while before that:

```
% npm info socket.io time | rg "^  '2"
⠙  '2.0.0': '2017-05-08T23:16:09.507Z',
  '2.0.1': '2017-05-08T23:41:33.138Z',
  '2.0.2': '2017-06-01T12:01:52.045Z',
  '2.0.3': '2017-06-12T12:06:19.959Z',
  '2.0.4': '2017-10-22T13:17:40.603Z',
  '2.1.0': '2018-03-29T21:33:53.997Z',
  '2.1.1': '2018-05-17T21:23:35.419Z',
  '2.2.0': '2018-11-28T23:16:12.591Z',
  '2.3.0': '2019-09-20T10:24:06.920Z',
  '2.4.0': '2021-01-04T23:28:15.549Z',
  '2.4.1': '2021-01-07T10:00:25.314Z',
  '2.5.0': '2022-06-26T07:50:09.027Z',
  '2.5.1': '2024-06-19T08:49:31.009Z'
```

Then when `socket.io@2.5.0` there is a *different* set of test failures.

Options:
1. dig into those test failures, or
2. skip testing of socket.io@2. That perhaps isn't a nice thing to do given socket.io themselves felt it worthwhile to do a 2.x release recently.

**Comment by trentm** [comment]
I'm going to temporarily remove the pkg:instr-socket.io label to try to get a test-all-versions run of all the other packages. I'd like to see if socket.io is the only failure to deal with.

**Comment by trentm** [comment]
Test status with the current state:
- `unit-test (22)` passes, e.g.: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/10079303119/job/27866318637?pr=2350
- `test-all-versions (22)` passes: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/10099991805/job/27930365577?pr=2350

This test-all-versions (TAV) run was with all packages **except instrumentation-socket.io**.

I'll now remove all `pkg:` labels except socket.io, so I can work on TAV for just that package.

**Comment by trentm** [comment]
Regarding the "fix a flaky test ..." commit above ^^:

`npm test` for instr-socket.io was failing something with Node.js 18 on my
laptop and (almost?) always with Node.js 20 and 22.
It was **not failing in `unit-test (18)` et al in CI**, just on my laptop.
My theory is as follows, though I didn't track it down to a full proof.

- My guess is this is a race.
- The 'traceReserved:true on is instrumented' test case: creates a socket.io
  server, then a client, then closes both immediate in a
  `client.on('connection')` handler.
- Using `process._getActiveHandles()` showed that in the hanging case there were two Timeout handles, which I think were preventing node from exiting.
- After some tracking, I think it is related to code in engine.io's "polling.js" ("node_modules/engine.io-client/build/cjs/transports/polling.js").
- That package uses the `debug` module so we can get some debug logging via:

```
DEBUG=engine.io-client:polling ../../../node_modules/.bin/ts-mocha -p tsconfig.json --require '@opentelemetry/contrib-test-utils'  test/socket.io.test.ts
```

- Apply this patch to just run the one test case:

```diff
diff --git a/plugins/node/instrumentation-socket.io/test/socket.io.test.ts b/plugins/node/instrumentation-socket.io/test/socket.io.test.ts
index 0b733a43..5f3842b4 100644
--- a/plugins/node/instrumentation-socket.io/test/socket.io.test.ts
+++ b/plugins/node/instrumentation-socket.io/test/socket.io.test.ts
@@ -190,7 +190,7 @@ describe('SocketIoInstrumentation', () => {
       });
     });

-    it('traceReserved:true on is instrumented', done => {
+    it.only('traceReserved:true on is instrumented', done => {
       const config: SocketIoInstrumentationConfig = {
         traceReserved: true,
         // only for v2: v2 emits [dis]connect[ing] events which later versions do not
```

- A hanging test run looks like this:

```
% DEBUG=engine.io-client:polling npm test

> @opentelemetry/instrumentation-socket.io@0.41.0 test
> ts-mocha -p tsconfig.json --require '@opentelemetry/contrib-test-utils' 'test/**/*.test.ts'

  SocketIoInstrumentation
    Server
  engine.io-client:polling polling +0ms
  engine.io-client:polling xhr poll +0ms
  engine.io-client:polling xhr open GET: http://localhost:50899/socket.io/?EIO=4&transport=polling&t=P3h-1Sp&b64=1 +0ms
  engine.io-client:polling xhr data null +1ms
  engine.io-client:polling polling got data 0{"sid":"HtOfGvDbgou28RruAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000} +11ms
  engine.io-client:polling xhr open POST: http://localhost:50899/socket.io/?EIO=4&transport=polling&t=P3h-1S_&b64=1&sid=HtOfGvDbgou28RruAAAA +0ms
  engine.io-client:polling xhr data 40 +0ms
  engine.io-client:polling polling +1ms
  engine.io-client:polling xhr poll +0ms
  engine.io-client:polling xhr open GET: http://localhost:50899/socket.io/?EIO=4&transport=polling&t=P3h-1T0&b64=1&sid=HtOfGvDbgou28RruAAAA +0ms
  engine.io-client:polling xhr data null +0ms
  engine.io-client:polling transport open - closing +6ms
  engine.io-client:polling writing close packet +0ms
  engine.io-client:polling xhr open POST: http://localhost:50899/socket.io/?EIO=4&transport=polling&t=P3h-1T6&b64=1&sid=HtOfGvDbgou28RruAAAA +0ms
  engine.io-client:polling xhr data 1 +0ms
      ✓ traceReserved:true on is instrumented

  1 passing (26ms)
```

- A passing test looks like this:

```
% DEBUG=engine.io-client:polling npm test

> @opentelemetry/instrumentation-socket.io@0.41.0 test
> ts-mocha -p tsconfig.json --require '@opentelemetry/contrib-test-utils' 'test/**/*.test.ts'

  SocketIoInstrumentation
    Server
  engine.io-client:polling polling +0ms
  engine.io-client:polling xhr poll +0ms
  engine.io-client:polling xhr open GET: http://localhost:50912/socket.io/?EIO=4&transport=polling&t=P3h-AGp&b64=1 +1ms
  engine.io-client:polling xhr data null +0ms
  engine.io-client:polling polling got data 0{"sid":"H3oNtujjJ0Q7OPGNAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000} +7ms
  engine.io-client:polling xhr open POST: http://localhost:50912/socket.io/?EIO=4&transport=polling&t=P3h-AGx&b64=1&sid=H3oNtujjJ0Q7OPGNAAAA +1ms
  engine.io-client:polling xhr data 40 +0ms
  engine.io-client:polling polling +1ms
  engine.io-client:polling xhr poll +0ms
  engine.io-client:polling xhr open GET: http://localhost:50912/socket.io/?EIO=4&transport=polling&t=P3h-AGy&b64=1&sid=H3oNtujjJ0Q7OPGNAAAA +0ms
  engine.io-client:polling xhr data null +0ms
      ✓ traceReserved:true on is instrumented
  engine.io-client:polling transport open - closing +6ms
  engine.io-client:polling writing close packet +0ms
  engine.io-client:polling xhr open POST: http://localhost:50912/socket.io/?EIO=4&transport=polling&t=P3h-AH2&b64=1&sid=H3oNtujjJ0Q7OPGNAAAA +0ms
  engine.io-client:polling xhr data 1 +0ms
  engine.io-client:polling polling got data 40{"sid":"jKQIHl4IYdeP0Vc1AAAB"} +0ms

  1 passing (22ms)
```

Notably: `polling got data 40{"sid":"jKQIHl4IYdeP0Vc1AAAB"}`

- My *guess* is that those `xhr open POST` calls from "polling.js" have no timeout, hold a reference that keeps the node process alive, and do not ever get a response because the test code has `close()`d the server and/or client.


The workaround I've used is to move the `.close()` calls in to a 10ms timeout.
This is unsatisfying, because I don't fully understand. I don't really want to
debug the polling behaviour of engine.io.

**Comment by trentm** [comment]
The next test failure in instr-socket.io TAV tests is with socket.io@2.5.1 and Node.js 22. It is summarized here: https://gist.github.com/trentm/507fd6a7e372ff88855b2027e8bd4c6a

I cannot reproduce it with other Node.js versions.

Curiously (luckily?) the same type of fix/workaround made to the test case for the earlier socket.io.test.ts failure seems to work here. See the just made commit 398ddb1.

This isn't very satisfying because I've not dug in to grok the issue.

**Comment by trentm** [comment]
Now I re-added all the pkg: labels to get a full TAV test run.

**Review by pichlermarc — APPROVED** [review]
looks great - all tests are passing, thank you for working on this :+1:

**Review by JamieDanielson — APPROVED** [review]
Thanks for the detailed notes around the test changes. I think the overall benefit of this test is enough to move forward in merging. If anything a TODO could be added to the test linking back to this for a later investigation, but I don't see it being worthwhile enough to keep digging into the polling behavior.

**Pull request merged**
