### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>@opentelemetry/auto-instrumentations-node: 0.36.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-fs bumped from ^0.7.0 to ^0.7.1
    * @opentelemetry/instrumentation-graphql bumped from ^0.33.1 to ^0.33.2
    * @opentelemetry/instrumentation-ioredis bumped from ^0.33.2 to ^0.34.0
    * @opentelemetry/instrumentation-koa bumped from ^0.34.1 to ^0.34.2
    * @opentelemetry/instrumentation-pg bumped from ^0.34.1 to ^0.35.0
    * @opentelemetry/instrumentation-redis bumped from ^0.34.2 to ^0.34.3
    * @opentelemetry/instrumentation-redis-4 bumped from ^0.34.2 to ^0.34.3
</details>

<details><summary>@opentelemetry/auto-instrumentations-web: 0.31.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-document-load bumped from ^0.31.1 to ^0.31.2
</details>

<details><summary>instrumentation-document-load: 0.31.2</summary>

### Bug Fixes

* remove component attribute from instrumentations ([#1399](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1399)) ([e93a192](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e93a192b672c8db361bac83ad60294ca49b95361))
</details>

<details><summary>instrumentation-fs: 0.7.1</summary>

### Bug Fixes

* **instrumentation-fs:** allow realpath.native and realpathSync.native ([#1332](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1332)) ([ee0a59a](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/ee0a59a59e94743b9411e10c09720a82c6586eb4))
* **instrumentation-fs:** fix instrumentation of `fs/promises` ([#1375](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1375)) ([3ca874e](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/3ca874e45ebf4623e76cbe9305e55e820b6e03fd))
</details>

<details><summary>instrumentation-graphql: 0.33.2</summary>

### Bug Fixes

* remove component attribute from instrumentations ([#1399](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1399)) ([e93a192](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e93a192b672c8db361bac83ad60294ca49b95361))
</details>

<details><summary>instrumentation-ioredis: 0.34.0</summary>

### Features

* **ioredis:** Update instrumentation-ioredis to version 5.x.x ([#1121](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1121)) ([f5f7ac6](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/f5f7ac6196b5422e030a6913c491117a6a3a0690))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/redis-common bumped from ^0.34.0 to ^0.35.0
</details>

<details><summary>instrumentation-koa: 0.34.2</summary>

### Bug Fixes

* remove component attribute from instrumentations ([#1399](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1399)) ([e93a192](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e93a192b672c8db361bac83ad60294ca49b95361))
</details>

<details><summary>instrumentation-long-task: 0.32.2</summary>

### Bug Fixes

* remove component attribute from instrumentations ([#1399](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1399)) ([e93a192](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/e93a192b672c8db361bac83ad60294ca49b95361))
</details>

<details><summary>instrumentation-pg: 0.35.0</summary>

### Features

* **pg:** remove support for pg v7 ([#1393](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1393)) ([ae6d4f3](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/ae6d4f39fc882d16e65e846218a69fb72586de3e))

### Bug Fixes

* **postgres:** pass 'arguments' to the connect callback ([#1395](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1395)) ([b02775f](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/b02775f0d9e84dea5463bb9a3883d0ad6ff1f500))
</details>

<details><summary>@opentelemetry/instrumentation-redis: 0.34.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/redis-common bumped from ^0.34.0 to ^0.35.0
</details>

<details><summary>@opentelemetry/instrumentation-redis-4: 0.34.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/redis-common bumped from ^0.34.0 to ^0.35.0
</details>

<details><summary>redis-common: 0.35.0</summary>

### Features

* **ioredis:** Update instrumentation-ioredis to version 5.x.x ([#1121](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1121)) ([f5f7ac6](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/f5f7ac6196b5422e030a6913c491117a6a3a0690))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by blumamir — APPROVED** [review]

**Comment by dyladan** [comment]
@blumamir re-running the test didn't fix it. are you aware of a problem blocking the browser tests in contrib?

**Comment by pichlermarc** [comment]
@dyladan Looks like the issue may be similar to what we had with windows tests in the core repo https://github.com/open-telemetry/opentelemetry-js/pull/3642. I'll look into into applying the same fix here. :thinking:

**Comment by pichlermarc** [comment]
I opened a PR to fix the browser tests :slightly_smiling_face: - turned out to be a similar problem as we had in core after all #1419

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.36.4 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-web-v0.31.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/redis-common-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fs-v0.7.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.33.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-ioredis-v0.34.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-koa-v0.34.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pg-v0.35.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-v0.34.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-redis-4-v0.34.3 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-document-load-v0.31.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-long-task-v0.32.2 :sunflower:

**Pull request merged**
