### PR TITLE
test(nestjs-core): fixed nestjs-core tav to work on all node versions

### PR DESCRIPTION
**Pull request by osherv**
## Which problem is this PR solving?

test-all-versions for node8 failed on nestjs-core@8 tests.
Here's the error:
https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8134447972?check_suite_focus=true

Pinning the tests to version 8.0.0 fix the problem, and now it works for all node versions.

- [x] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.

### CODE REVIEW

**Comment by dyladan** [comment]
We're not getting the latest versions of these dependencies in our tests now though right? Isn't it better to test in an environment as similar to what a user would see as possible? It might be better to drop node 8 testing

/cc @open-telemetry/javascript-maintainers

**Comment by osherv** [comment]
@dyladan yes you're right. Maybe it's better to remove the whole node8 support.
Let me know if that's preferred :)

**Comment by dyladan** [comment]
Waiting to hear what other maintainers think but removing node 8 is probably the way to go

**Comment by osherv** [comment]
@dyladan @Rauno56 According to this pr: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1065
I think that you agree that the best this is to remove the support for tav in node8.

**Comment by blumamir** [comment]
Thank you @osherv for fixing this.

I support dropping node8 support for nest-js instrumentation, but it seems that nestjs (at least with latest version 9) [suuports node >= 12.9.0](https://github.com/nestjs/nest/blob/8d66cece7990fa6fd74c75dea87d76def0920cb1/package.json#L176). So it should fail on node10 as well, right? any idea why we see problem for node8 only?

**Comment by osherv** [comment]
@blumamir Thanks :)
I have no idea, i can dig into this, but we can drop this version as well XD

**Comment by Rauno56** [comment]
@osherv, I agree - let's add skip for 10 as well and merge this.

**Comment by osherv** [comment]
@Rauno56 Thanks, added 10 version

**Review by Rauno56 — APPROVED** [review]

**Pull request merged**
