### PR TITLE
feat: AWS-SDK SNS Context propagation

### PR DESCRIPTION
**Pull request by habmic**
## Which problem is this PR solving?

- AWS SNS doesn't propagation the context

## Short description of the changes

- Adds support for sending the context via SNS Message attributes (same as SQS does)
- It uses the same logic as SQS

### CODE REVIEW

**Review by blumamir — APPROVED** [review]
LGTM

**Comment by obecny** [comment]
was there already an issue created for that previously ? (if so pls link it, otherwise ignore my comment)

**Comment by habmic** [comment]
> was there already an issue created for that previously ? (if so pls link it, otherwise ignore my comment)

There isn't a related issue

**Comment by blumamir** [comment]
This PR is open for 4 days and I reviewed and approved it as component owner of the instrumentation.
I encourage more reviewers, but if no one is planning to take a look - what do you think about merging and publishing this one?

**Comment by obecny** [comment]
@blumamir aren't you able to merge it yrself ?

**Comment by blumamir** [comment]
> @blumamir aren't you able to merge it yrself ? I mean do you have this option available ?

I do. merging it, Thanks

**Pull request merged**
