### PR TITLE
chore: test on node 14

### LINKED ISSUE #22: Build: Use node 14 instead of node 13
Similar to https://github.com/open-telemetry/opentelemetry-js/issues/996

/cc @dyladan

### PR DESCRIPTION
**Pull request by dyladan**
Fixes #22

### CODE REVIEW

**Comment by dyladan** [comment]
hmm @mayurkale22 wdyt? AFAIK 13 essentially is 14, but with the API not completely finalized yet. Obviously there are differences though since our tests are passing in 13 but not 14.

**Comment by mayurkale22** [comment]
> hmm @mayurkale22 wdyt? AFAIK 13 essentially is 14, but with the API not completely finalized yet. Obviously there are differences though since our tests are passing in 13 but not 14.

Maybe we can keep both and remove 13 after `2020-06-01`?

**Comment by dyladan** [comment]
I will update the PR, and will make a PR to have same behavior in core. We still need to figure out why pg fails on 14

**Comment by obecny** [comment]
@dyladan can you please resolve conflicts ?

**Comment by dyladan** [comment]
> @dyladan can you please resolve conflicts ?

I'll do this today

**Pull request merged**
