### PR TITLE
fix(detectors): reduce diag level on detectors failing to detect

### LINKED ISSUE #2268: Reduce log level on detectors failing to detect
I've noticed that some detectors make use of `diag.info` or `diag.warn` when they fail to do the detection. So with the default log level they are displayed in stdout.

A couple of places where it happens

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/6721bddc2d190befabab95f706ca467d06633674/detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts#L116

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/6721bddc2d190befabab95f706ca467d06633674/detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts#L91

This is not a problem per se but these messages appear if the customer enables some detectors that for sure will fail. Some examples:
- app is started enabling container detector but not deployed in a container
- app is started enabling AWS detector but deployed in another cloud
- app is started with `OTEL_NODE_RESOURCE_DETECTORS=all` when using auto instrumentations

IMHO seeing messages about AWS when my app is running in another cloud could be a bit misleading. I'm attaching here a small repro

package.json
```json
{
  "name": "detectors-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@opentelemetry/api": "^1.9.0",
    "@opentelemetry/auto-instrumentations-node": "^0.47.0"
  }
}
```

index.js
```js
// Usage:
//  OTEL_NODE_RESOURCE_DETECTORS=all node --require '@opentelemetry/auto-instrumentations-node/register' index.js

const https = require('https');

const clientReq = https.request('https://opentelemetry.io/', function (cres) {
  console.log('client response: %s %s', cres.statusCode, cres.headers);
  const chunks = [];
  cres.on('data', function (chunk) {
      chunks.push(chunk);
  });
  cres.on('end', function () {
      const body = chunks.join('');
      console.log('client response body lenght: %j', body.length);
  });
});
clientReq.end();
```

And this is what you get
```sh
OTEL_NODE_RESOURCE_DETECTORS=all node --require '@opentelemetry/auto-instrumentations-node/register' index.js

OTEL_TRACES_EXPORTER is empty. Using default otlp exporter.
OpenTelemetry automatic instrumentation started successfully
Container Detector failed to read the Container ID:  ENOENT: no such file or directory, open '/proc/self/cgroup'
Process is not running on K8S [Error: ENOENT: no such file or directory, access '/var/run/secrets/kubernetes.io/serviceaccount/token'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/var/run/secrets/kubernetes.io/serviceaccount/token'
}
client response: 200 {
  ...
  connection: 'close'
}
client response body lenght: 20669
```

The K8s message is scary if you're not familiar with the topic. Detectors just resolved that they're nor running in a container neither in an AWS cluster. So my proposal would be:
- reduce the level to `debug`
- rephrase the messages

### PR DESCRIPTION
**Pull request by johnli-developer**
## Which problem is this PR solving?

- Fix #2268 

## Short description of the changes

- change log from warn to debug when detector failed to detect

### CODE REVIEW

**Comment by david-luna** [comment]
@johnli-developer thanks for contributing to the project :) 

I see some other places in detectors where `diag.warn` is still used. Is this PR a work in progress?

**Comment by johnli-developer** [comment]
> @johnli-developer thanks for contributing to the project :)
> 
> I see some other places in detectors where `diag.warn` is still used. Is this PR a work in progress?

This PR is complete it's change to debug for detectors. Which one would you also like to change to debug?

**Comment by trentm** [comment]
Here are some other ones:

```
% rg 'diag\.(info|warn)' detectors
detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts
65:      diag.info(
131:        diag.info(

detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetectorSync.ts
140:      diag.warn('AwsEcsDetector failed to read container ID', e);

detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetectorSync.ts
98:      diag.warn('Process is not running on K8S', e);
141:      diag.warn('Cannot get cluster name on EKS', e);
157:      diag.warn('Unable to read Kubernetes client token.', e);
192:      diag.warn(`AwsEksDetector failed to read container ID: ${e.message}`);
```

That doesn't mean that this PR has to deal with all of them. But it won't "Fix: #2268" unless it gets all of them.

**Comment by johnli-developer** [comment]
> Here are some other ones:
> 
> ```
> % rg 'diag\.(info|warn)' detectors
> detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts
> 65:      diag.info(
> 131:        diag.info(
> 
> detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetectorSync.ts
> 140:      diag.warn('AwsEcsDetector failed to read container ID', e);
> 
> detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetectorSync.ts
> 98:      diag.warn('Process is not running on K8S', e);
> 141:      diag.warn('Cannot get cluster name on EKS', e);
> 157:      diag.warn('Unable to read Kubernetes client token.', e);
> 192:      diag.warn(`AwsEksDetector failed to read container ID: ${e.message}`);
> ```
> 
> That doesn't mean that this PR has to deal with all of them. But it won't "Fix: #2268" unless it gets all of them.

Sure, I will update them

**Review by trentm — APPROVED** [review]
Looks good. Thanks.
From the original issue:

> So my proposal would be:
>
>    reduce the level to debug
>    rephrase the messages


This handles the first point: reducing to `diag.debug`.

I think the messages could benefit from some rephrasing to be less concerning, even for the user that has OTEL_LOG_LEVEL set to debug. However that could be done in a separate PR.

**Comment by trentm** [comment]
@johnli-developer I've set this up to merge when the PR is updated to the base branch.  It looks like your fork repo doesn't allow me the access to do that. Can you update the base branch on this PR? I *think* the GitHub UI will show an "Update Branch" button for you.

**Comment by johnli-developer** [comment]
> @johnli-developer I've set this up to merge when the PR is updated to the base branch. It looks like your fork repo doesn't allow me the access to do that. Can you update the base branch on this PR? I _think_ the GitHub UI will show an "Update Branch" button for you.
@trentm I clicked that update branch button, is it OK now?

**Review by pichlermarc — APPROVED** [review]

**Pull request merged**
