### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@opentelemetry/instrumentation-aws-sdk: 0.3.0</summary>

### Features

* config option to extract sqs context from message payload ([#737](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/737)) ([28e2113](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/28e2113ec1091e73a1d1b62b48fee8c01c72afee))
</details>
<details><summary>@opentelemetry/instrumentation-koa: 0.27.0</summary>

### Features

* **koa:** add a config option to allow layers to be ignored by type ([#646](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/646)) ([572ed66](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/572ed665ea4ac93082c347f7179d67e9a8fe19b8))
</details>
<details><summary>@opentelemetry/instrumentation-pino: 0.27.0</summary>

### Features

* **instrumentation-pino:** bump supported pino version to v7.x ([#724](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/724)) ([aff24b8](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/aff24b82e2654d6c42e1a9b03351dd94b9869793))
</details>
<details><summary>@opentelemetry/auto-instrumentations-node: 0.26.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-koa bumped from ^0.26.0 to ^0.27.0
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by blumamir — APPROVED** [review]

**Review by obecny — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/auto-instrumentations-node is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.26.2 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-aws-sdk is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.3.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-koa is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-koa-v0.27.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-pino is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pino-v0.27.0 :sunflower:

**Pull request merged**
