### PR TITLE
chore: update to OTel 0.15.0

### PR DESCRIPTION
**Pull request by Flarna**
## Which problem is this PR solving?

Fixes: #311
Fixes: #309
Fixes: #314
Fixes: #308

## Short description of the changes

Update all dependencies to 0.15.0 and adapt code to changed APIs.

### CODE REVIEW

**Review by vmarchaud — APPROVED** [review]
lgtm, just need CI green

**Comment by Flarna** [comment]
pushed a fixup to get the document load test green. But I must admit that I have no idea why it failed and if the changes I did to get it green are correct.

@obecny I think you created the plugin initially. Would be nice if you could take a look.

**Comment by Flarna** [comment]
Please note also that I haven't touched examples here because they refer to concrete versions of packages. Therefore I think this should be done via a separate PR short before creating the next release.

**Review by johnbley — APPROVED** [review]
lgtm

**Review by naseemkullah — APPROVED** [review]

**Review by obecny — APPROVED** [review]
lgtm

**Comment by obecny** [comment]
> pushed a fixup to get the document load test green. But I must admit that I have no idea why it failed and if the changes I did to get it green are correct.
> 
> @obecny I think you created the plugin initially. Would be nice if you could take a look.

it failed because there was also a change in web so one more resource is being reported now, fix is fine

**Review by dyladan — APPROVED** [review]

**Pull request merged**
