### PR TITLE
chore: bump codecov

### PR DESCRIPTION
**Pull request by dyladan**
Bump codecov to 3.7.1

### CODE REVIEW

**Comment by dyladan** [comment]
@open-telemetry/javascript-maintainers this is just a dependency update from a security alert. would appreciate a swift merge.

**Comment by obecny** [comment]
> @open-telemetry/javascript-maintainers this is just a dependency update from a security alert. would appreciate a swift merge.
Yea, I'm wondering why it created so many small PR, I thought it was already resolved so it should just one PR

**Comment by dyladan** [comment]
It's because it's a security update. They're handled separately. The PRs are only visible by maintainers too, its an entirely different mechanism.

**Comment by obecny** [comment]
> It's because it's a security update. They're handled separately. The PRs are only visible by maintainers too, its an entirely different mechanism.

PRs are public only yellow warnings are visible for maintainers on "code tab"

**Comment by dyladan** [comment]
@open-telemetry/javascript-maintainers this is just a dep PR and I would like to merge it

**Pull request merged**
