### PR TITLE
chore: bump opentelemetry core dependencies

### PR DESCRIPTION
**Pull request by dyladan**

### CODE REVIEW

**Comment by dyladan** [comment]
@obecny looks like the user interaction plugin is failing on the latest core

**Comment by dyladan** [comment]
Looks like attributes.component is still in the assertions, but was removed from the xhr plugin in core.

**Comment by obecny** [comment]
Missing: examples, lerna.json, main package.json

**Comment by dyladan** [comment]
@obecny this is not the release proposal. this is pumping the dependencies

**Comment by obecny** [comment]
> @obecny this is not the release proposal. this is pumping the dependencies

but in examples should we also update to latest ?

**Comment by dyladan** [comment]
> > @obecny this is not the release proposal. this is pumping the dependencies
> 
> but in examples should we also update to latest ?

Done

**Pull request merged**
