### PR TITLE
fix(instrumentation-mysql): fix test for mysql2 v3 (#2168)

### LINKED ISSUE #2168: mysql2 - migrate to v3 in tests
renovate opened up #2095 to upgrade `mysql2` package to a new version 3.

While we only use it for tests, the security warning is not a concern for us, but the tests are not compiling with the new version as a dev dependency:

```
> @opentelemetry/instrumentation-mysql2@0.37.0 compile
> tsc -p .

test/mysql.test.ts:145:29 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(group: string, connectionUri: string): void', gave the following error.
    Argument of type 'PoolClusterOptions' is not assignable to parameter of type 'string'.
  Overload 2 of 3, '(group: string, config: PoolOptions): void', gave the following error.
    Type 'PoolClusterOptions' has no properties in common with type 'PoolOptions'.

145     poolCluster.add('name', {
                                ~
146       port,
    ~~~~~~~~~~~
... 
150       database,
    ~~~~~~~~~~~~~~~
151     } as mysqlTypes.PoolClusterOptions);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Found 1 error.

npm ERR! Lifecycle script `compile` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @opentelemetry/instrumentation-mysql2@0.37.0 
npm ERR!   at location: /Users/amirblum/repos/opentelemetry-js-contrib/plugins/node/opentelemetry-instrumentation-mysql2 
```

Not sure how tav is working properly.

In npm, seems that version 3 is the popular version, and v2 has security issues. So it does make sense to use the new version in instrumentation testing by default.

This issue closes #2095 which cannot merge, to track the task of upgrading the dev dependency to a more relevant version

### PR DESCRIPTION
**Pull request by tpraxl**
## Which problem is this PR solving?

Fixes #2168 - migrate to v3 in tests

## Short description of the changes

Update mysql2 dependency to latest version (@3.11.3) and fix tests. Problems during `npm run compile` were fixed by removing an unsafe and incorrect typecast.

### CODE REVIEW

**Comment by tpraxl** [comment]
Hold on. I was mislead. While the mysql2 tests do compile now and they signaled success during `npm test`, all of them were actually skipped (see `process.env.RUN_MYSQL_TESTS_LOCAL` and `process.env.RUN_MYSQL_TESTS`).

I really think you should generally separate skipped tests from succeeded tests in the output.

I only noticed that, because I actually want to fix #1511 and started to work on that.

Let's see if I can fix the tests when they are not skipped. Might take a while, depending on the time I can spare. In the meantime: Should I close this PR or do you want to keep it open?

**Comment by tpraxl** [comment]
The tests succeeded (except for fastify and mongoose), once I figured out that I need to  export `RUN_MYSQL_TESTS="true"` in order for otherwise skipped tests not to signal that they succeeded,  AND have a docker container running with exact these arguments:

`````
podman run --rm -d --name otel-mysql -p 33306:3306 -e MYSQL_ROOT_PASSWORD=rootpw -e MYSQL_DATABASE=test_db -e MYSQL_USER=otel -e MYSQL_PASSWORD=secret mysql:5.7 --log_output=TABLE --general_log=ON
``````

(Where `general_log=ON`  is necessary for some tests that failed before)

You should mention that somewhere in the README under "How to run tests the right way".

This PR is now ready for review.

**Review by david-luna — COMMENTED** [review]
LGTM. Thanks for contributing to OpenTelemetry :)

@haddasbronfman any feedback?

**Comment by tpraxl** [comment]
> This package does not have an assigned [component owner](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/CONTRIBUTING.md#component-ownership) and is considered [unmaintained](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/CONTRIBUTING.md#unmaintained). As such this package is in feature-freeze and this PR will be closed with 14 days unless a new owner or a sponsor (a member of @open-telemetry/javascript-approvers) for the feature is found. It is the responsibility of the author to find a sponsor for this feature. Are you familiar with this package? Consider [becoming a component owner](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/CONTRIBUTING.md#becoming-a-component-owner).

Uh.. can anyone explain what happened? How likely is this PR being closed in 14 days?

**Comment by maryliag** [comment]
@tpraxl this message is automatic for all unmaintained packages, to make it clear we won't accept new features unless there is a new code owner for it, but we're still accepting fixes, so we would be able to merge your PR, is just a matter of getting the approval and a maintainer merging it. 
In case it doesn't happen and it gets closed 14 days, you can just re-open and poke someone with the permissions to merge this for you :)

**Review by blumamir — APPROVED** [review]
Thanks @tpraxl !

Please fix the conflicts and then I'll merge

**Pull request merged**
