### PR TITLE
fix(package.json): publish source maps

### PR DESCRIPTION
**Pull request by blumamir**
## Which problem is this PR solving?

- publish source maps files to npm. This is already enabled in some of the packages in this repo (but missing in others), and was [added to core repo](https://github.com/open-telemetry/opentelemetry-js/pull/1237) a year ago:

## Short description of the changes

- add "build/src/**/*.js.map" to "files" section in package.json

### CODE REVIEW

**Comment by Flarna** [comment]
Shouldn't we include the ts files also?
At least VsCode complains that it can't find ts files if there are source map files pointing to "nowhere".

**Comment by blumamir** [comment]
> Shouldn't we include the ts files also?
> At least VsCode complains that it can't find ts files if there are source map files pointing to "nowhere".

Don't really know, 
I fix this due to warnings about missing source map files in one of our client's IDE, which was solved by adding the js.map files to npm publish.
I remember it was missing in core and then added in [the PR I mentioned above](https://github.com/open-telemetry/opentelemetry-js/pull/1237). Then we added it to the instrumentations in ext-js [here](https://github.com/aspecto-io/opentelemetry-ext-js/pull/147) and the warning went away for these packages.
The packages from the contrib still generate warnings about missing source map files which I believe will also be solved if we include the ".js.map" in the distribution.

**Comment by MSNev** [comment]
> Shouldn't we include the ts files also?

If we change the ```sourceMap``` in the tsconfig.json to ```inlineSourceMap``` then no as the generated sourcemap will then contain the original source. While this makes the *.map files huge its a lot easier to handle as it includes the original code.

I'm not sure about any other packaging switches / tools that would also need additional config changes to retain these (like webpack for example).

**Review by obecny — APPROVED** [review]
lgtm

**Review by MSNev — APPROVED** [review]

**Review by vmarchaud — APPROVED** [review]

**Pull request merged**
