### PR TITLE
fix(host-metrics): widen MeterProvider type restriction in BaseMetrics class

### PR DESCRIPTION
**Pull request by brianphillips**
Instead of requiring the `MeterProvider` class implementation as exported by `@opentelemetry/sdk-metrics`, change to simply require the `MeterProvider` interface as exported by `@opentelemtry/api`. This makes `HostMetrics` easier to initialize with the meter provider returned by `metrics.getMeterProvider()`

## Which problem is this PR solving?

Initializing the `HostMetrics` object with a `meterProvider` as returned by `metrics.getMeterProvider()` files a type check:

```typescript
import { metrics } from "@opentelemetry/api";
import { HostMetrics } from "@opentelemetry/host-metrics";

const hostMetrics = new HostMetrics({ meterProvider: metrics.getMeterProvider() }); // <-- fails with TS2739
```

The compile-time error is:

```
Type 'MeterProvider' is missing the following properties from type 'MeterProvider': _sharedState, _shutdown, addMetricReader, shutdown, forceFlush [2739]
```

## Short description of the changes

Instead of requiring the `MeterProvider` class implementation as exported by `@opentelemetry/sdk-metrics`, I've changed the `BaseMetrics` abstract class to simply require the `MeterProvider` interface as exported by `@opentelemtry/api`. This matches the existing behavior where, if no `meterProvider` is specified, it uses `metrics.getMeterProvider()` as the default (but emits a warning).

### CODE REVIEW

**Review by pichlermarc — APPROVED** [review]
yep that's better - thanks :+1:

**Comment by pichlermarc** [comment]
> yep that's better - thanks 👍 Note: waiting for @legendecas approval before merging (component owner) 🙂

(actually @legendecas is out of office for a bit so I'll just merge this - the change seems straight-forward enough) :slightly_smiling_face:

**Review by legendecas — APPROVED** [review]
Thanks!

**Comment by legendecas** [comment]
Does the CLA needs to be signed, or is the CLA bot not working?

**Comment by brianphillips** [comment]
> Does the CLA need to be signed, or is the CLA bot not working?

@legendecas - I (my company) has already signed the CLA and the commit that I originally pushed shows that the status changed. I'm not sure why merging `main` into this PR isn't showing a :heavy_check_mark:

**Pull request merged**
