### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@opentelemetry/browser-extension-autoinjection: 0.27.1</summary>

### Bug Fixes

* fastify and browser autoinjection failed to compile ([#793](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/793)) ([c08efa8](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/c08efa82a38d3d5b4d0c51d712a39052317b9f74))
</details>
<details><summary>@opentelemetry/host-metrics: 0.27.0</summary>

### Features

* update host-metrics to api-metrics v0.27.0 ([#779](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/779)) ([9cef8a7](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/9cef8a7e3a8cb358fd0095b64cbef3874ffee517))
</details>
<details><summary>@opentelemetry/instrumentation-graphql: 0.27.1</summary>

### Bug Fixes

* early close of span with graphql execute ([#752](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/752)) ([4a3b410](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/4a3b4107e40845091a267e5452ea17eed8a9fdf6))
</details>
<details><summary>@opentelemetry/instrumentation-user-interaction: 0.28.0</summary>

### Features

* **user-interaction:** support for custom events and span enhancement ([#653](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/653)) ([27e37e3](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/27e37e38f983eabdae4f2cfe859d156440378e08))

### Bug Fixes

* **user-interaction:** handle null listener in addEventListener ([#765](https://www.github.com/open-telemetry/opentelemetry-js-contrib/issues/765)) ([aacfe82](https://www.github.com/open-telemetry/opentelemetry-js-contrib/commit/aacfe82c85a9aebb1fdf3e38521144be09625dc8))
</details>
<details><summary>@opentelemetry/auto-instrumentations-web: 0.27.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-user-interaction bumped from ^0.27.0 to ^0.28.0
</details>
<details><summary>@opentelemetry/auto-instrumentations-node: 0.27.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-graphql bumped from ^0.27.0 to ^0.27.1
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by vmarchaud — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/auto-instrumentations-node is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.27.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/auto-instrumentations-web is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-web-v0.27.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/browser-extension-autoinjection is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/browser-extension-autoinjection-v0.27.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/host-metrics is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/host-metrics-v0.27.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-graphql is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.27.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release for @opentelemetry/instrumentation-user-interaction is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-user-interaction-v0.28.0 :sunflower:

**Pull request merged**
