### PR TITLE
fix(pg): Do not replace argument with plain object

### PR DESCRIPTION
**Pull request by unflxw**
If the object given as a first argument contained a `.callback` property, the callback would be patch and the object in the argument array would be replaced with a plain object. If the object was a class, the prototype would be lost.

Instead, this implementation replaces the `.callback` property on the existing object, which is otherwise left as-is.

This fixes issue #1431, where `pg-copy-streams` provides a `Submittable` object with `.callback` and `.submit` methods defined in the class prototype. Because `.callback` exists, the object in the argument array is replaced with a plain object, containing the patched `.callback`, but no `.submit`.

Because `.submit` was no longer present, `pg` would not treat it as a submittable, causing it to attempt to execute the query by its `.text` property, and return `undefined` instead of the submittable.

### Notes

I dropped the logic to make a copy of the arguments because I'm not sure what the purpose of not modifying the original argument containing the callback is. If it's necessary to keep that, we might want to copy the prototype over to the reconstructed object in some other way.

### CODE REVIEW

**Comment by rauno56** [comment]
Thanks for the ping. Sorry for my absence. I'll take a look tomorrow.

**Comment by unflxw** [comment]
@rauno56 No hurry! Thanks for looking into it.

**Review by rauno56 — APPROVED** [review]
I'm reluctant of merging without passing tests, but the case you made is clear and makes sense.

**Comment by unflxw** [comment]
It seems that the test failures are unrelated, right?

**Comment by pichlermarc** [comment]
> It seems that the test failures are unrelated, right?

Yep they were unrelated, some lint issues remain that look related, though :slightly_smiling_face:

**Comment by unflxw** [comment]
@pichlermarc Whoops, fixed! Apologies for the delay :)

**Comment by unflxw** [comment]
I have rebased this against `main`. Can it be merged @pichlermarc @rauno56 @dyladan? 🥺🙏

**Comment by unflxw** [comment]
Thank you @dyladan!

**Pull request merged**
