### PR TITLE
fix(fastify): Make sure consturctor patching works with esm

### PR DESCRIPTION
**Pull request by mydea**
## Which problem is this PR solving?

instrumentation-fastify does not work in ESM mode. This PR fixes this so that fastify can be instrumented when using esm.

The underlying problem is that in ESM mode, the `moduleExports` is not === the fastify constructor. Instead, this can _only_ be found under the `default` key.

## Short description of the changes

This changes the wrapping behavior to always use the named `fastify` export, which should always exist.

Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1519

### CODE REVIEW

**Comment by Flarna** [comment]
Is there an impact to commonjs users using fastify like this (copied from fastify docs)?
```js
const fastify = require('fastify')({
  logger: true
})
```

**Comment by mydea** [comment]
> Is there an impact to commonjs users using fastify like this (copied from fastify docs)?
> 
> ```js
> const fastify = require('fastify')({
>   logger: true
> })
> ```

I've tried it in a small test app of mine where both syntaxes continue to work for CJS, but would appreciate if somebody else could also give it a go (due to the "mysterious" ways that these things sometimes work 😅 )

**Comment by pichlermarc** [comment]
@mydea thank you for your contribution. Would you mind signing the CLA? Then we can proceed with the PR. :slightly_smiling_face:

**Comment by mydea** [comment]
> @mydea thank you for your contribution. Would you mind signing the CLA? Then we can proceed with the PR. 🙂

Done!

**Review by pichlermarc — APPROVED** [review]
> > Is there an impact to commonjs users using fastify like this (copied from fastify docs)?
> > ```js
> > const fastify = require('fastify')({
> >   logger: true
> > })
> > ```
> 
> I've tried it in a small test app of mine where both syntaxes continue to work for CJS, but would appreciate if somebody else could also give it a go (due to the "mysterious" ways that these things sometimes work 😅 )

Looks good, thanks! :slightly_smiling_face: I also checked and it seems to work for me too.

It seems to need some adjustments so that `prettier` succeeds, though (see [here](https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/6001135065/job/16274673430?pr=1624#step:8:240), you can also run `npm run lint` from the `plugins/node/opentelemetry-instrumentation-fastify/` to check locally), then this should be good to go :slightly_smiling_face:

**Comment by mydea** [comment]
> > > Is there an impact to commonjs users using fastify like this (copied from fastify docs)?
> > > ```js
> > > const fastify = require('fastify')({
> > >   logger: true
> > > })
> > > ```
> > 
> > 
> > I've tried it in a small test app of mine where both syntaxes continue to work for CJS, but would appreciate if somebody else could also give it a go (due to the "mysterious" ways that these things sometimes work 😅 )
> 
> Looks good, thanks! 🙂 I also checked and it seems to work for me too.
> 
> It seems to need some adjustments so that `prettier` succeeds, though (see [here](https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/6001135065/job/16274673430?pr=1624#step:8:240), you can also run `npm run lint` from the `plugins/node/opentelemetry-instrumentation-fastify/` to check locally), then this should be good to go 🙂

ah, right, I ran `npm run lint:fix` and pushed the fix!

**Pull request merged**
