### PR TITLE
docs(multiple): update readme for semantic convention

### PR DESCRIPTION
**Pull request by raymonslickdeals**
## Which problem is this PR solving?

- updates #1778 

## Short description of the changes

- updates readme to include section for semantic convention for those readme that do not have semantic convention usage. 
- Following readme where updated:

1. plugins/node/instrumentation-dataloader/README.md
2. plugins/node/instrumentation-fs/README.md
3. plugins/web/opentelemetry-instrumentation-long-task/README.md
4. plugins/web/opentelemetry-instrumentation-user-interaction/README.md

### CODE REVIEW

**Review by JamieDanielson — APPROVED** [review]
Thanks for updating this!

**Comment by raymonslickdeals** [comment]
> Thanks for updating this!

It looks like this package does not have a component owner / maintainer thus blocking this PR.

**Comment by pichlermarc** [comment]
@raymonslickdeals all good, we can still merge it 🙂

**Pull request merged**
