### PR TITLE
fix(net.peer.port): net.peer.port needs to be a number not a string

### PR DESCRIPTION
**Pull request by esara**
I noticed that a number of contrib instrumentation populated the net.peer.port as a string parsed out of the connection string. This not only violates the semantic convensations, but in same cases causes and exception the the span attributes are parsed. https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/database.md#connection-level-attributes

## Which problem is this PR solving?
This is related to https://github.com/open-telemetry/opentelemetry-js-contrib/issues/781
More specifically, there is an inconsistency, where the port variable is a string in multiple instrumentation (memcached, mongodb, mysql/mysql2, mongodb) for example
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts#L802
compared to other instrumentation, where is correctly defined as an int (cassandra and others)
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-cassandra/src/instrumentation.ts#L179

## Short description of the changes
Making sure that the net.peer.port attribute is a number instead of a string

BEGIN_COMMIT_OVERRIDE
fix(instrumentation-memcached): parse attribute value for net.peer.port to a number
fix(instrumentation-mongodb): parse attribute value for net.peer.port to a number
fix(instrumentation-mysql): parse attribute value for net.peer.port to a number
fix(instrumentation-mysql2): parse attribute value for net.peer.port to a number
END_COMMIT_OVERRIDE

### CODE REVIEW

**Review by br-kearns — APPROVED** [review]

**Review by pichlermarc — APPROVED** [review]
Looks good! :slightly_smiling_face: 
Thanks for taking care of this. :slightly_smiling_face:

**Review by pichlermarc — CHANGES_REQUESTED** [review]
Ah looks like the tests also need to be updated (they assert that the values are `string`s, instead of `number`)

**Comment by esara** [comment]
> Ah looks like the tests also need to be updated (they assert that the values are `string`s, instead of `number`)

@pichlermarc let me know if the test look better now

**Comment by pichlermarc** [comment]
@esara, please don't force-push. It makes it hard to review the PR because the history disappears every time I check back :sweat_smile: 

(also makes it hard to see if the tests were passing as I have to dig into old workflow runs to find the run that was associated with the commit before the force-push)

**Review by pichlermarc — APPROVED** [review]

**Pull request merged**
