### PR TITLE
chore: update core and API

### PR DESCRIPTION
**Pull request by dyladan**

### CODE REVIEW

**Review by Flarna — APPROVED** [review]
a bot would be useful for such updates

**Comment by dyladan** [comment]
> a bot would be useful for such updates

I was thinking the same thing. These PRs are quite a lot of work now that the version numbers between core and contrib match. Simple find and replace schemes are very difficult now.

**Comment by vmarchaud** [comment]
I opened an issue at the time to try to automate this https://github.com/open-telemetry/opentelemetry-js-contrib/issues/457

**Review by vmarchaud — APPROVED** [review]

**Review by johnbley — APPROVED** [review]

**Review by MSNev — APPROVED** [review]

**Comment by obecny** [comment]
@dyladan Please don't merge such PR in future until the version from core 0.23 is released. I wanted to release patch for version 0.22 with fixed esm build and it is not possible now as the main branch already points to unreleased version of core 0.23.

**Comment by dyladan** [comment]
0.23 is released

**Comment by obecny** [comment]
> 0.23 is released

https://github.com/open-telemetry/opentelemetry-js it is still showing the latest to be 0.22, on screenshot you posted 0.22 is also marked as latest, shouldn't the 0.23 be latest ?

**Comment by obecny** [comment]
npm install @opentelemetry/core --save-dev and it will install 0.22

**Comment by dyladan** [comment]
If we make `0.23.0` latest then if a user does `npm i @opentelemetry/node` they will get `0.23.0` which is incompatible with the latest contrib. The last few releases were done this way. You can get 0.23 if you specifically ask for it like `npm i @opentelemetry/node@0.23.0` or `npm i @opentelemetry/node@next`. The core release `latest` tag is always compatible with the contrib release `latest` tag. When contrib is released, the `next` tag is changed to latest.


> npm install @opentelemetry/core --save-dev and it will install 0.22

Yes, that's on purpose

**Comment by dyladan** [comment]
If we apply the `latest` tag to core 0.23 and user does `npm install @opentelemetry/node @opentelemetry/instrumenation-mysql` they will get incompatible versions. With the current scheme it still works.

**Comment by obecny** [comment]
ok got it, thx

**Comment by dyladan** [comment]
We've done this for the last few releases. Users get confused if they install latest everything then get errors that versions aren't compatible.

**Comment by obecny** [comment]
any reason of not releasing the version contrib `0.23` yet ?

**Comment by obecny** [comment]
> If we make `0.23.0` latest then if a user does `npm i @opentelemetry/node` they will get `0.23.0` which is incompatible with the latest contrib. The last few releases were done this way. You can get 0.23 if you specifically ask for it like `npm i @opentelemetry/node@0.23.0` or `npm i @opentelemetry/node@next`. The core release `latest` tag is always compatible with the contrib release `latest` tag. When contrib is released, the `next` tag is changed to latest.
> 
> > npm install @opentelemetry/core --save-dev and it will install 0.22
> 
> Yes, that's on purpose

what  about https://github.com/open-telemetry/opentelemetry-js/releases, shouldn't the release 0.23 be visible here too ?

**Comment by dyladan** [comment]
oops yes i'll fix it

**Comment by dyladan** [comment]
https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.23.0

**Pull request merged**
