### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by dyladan**
:robot: I have created a release *beep* *boop*
---

<details><summary>@opentelemetry/auto-instrumentations-node: 0.32.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @opentelemetry/instrumentation-aws-sdk bumped from ^0.9.0 to ^0.9.1
    * @opentelemetry/instrumentation-express bumped from ^0.31.0 to ^0.31.1
    * @opentelemetry/instrumentation-graphql bumped from ^0.30.0 to ^0.31.0
    * @opentelemetry/instrumentation-ioredis bumped from ^0.32.0 to ^0.32.1
    * @opentelemetry/instrumentation-mysql bumped from ^0.31.0 to ^0.31.1
    * @opentelemetry/instrumentation-net bumped from ^0.30.0 to ^0.30.1
    * @opentelemetry/instrumentation-pg bumped from ^0.31.0 to ^0.31.1
    * @opentelemetry/instrumentation-pino bumped from ^0.31.0 to ^0.32.0
    * @opentelemetry/instrumentation-redis-4 bumped from ^0.32.0 to ^0.33.0
</details>

<details><summary>instrumentation-aws-sdk: 0.9.1</summary>

### Bug Fixes

* avoid type imports of the aws-sdk package in the built assets ([#1066](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1066)) ([457be50](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/457be5035b9ba87211fe3553c901b7408dd2d593))
</details>

<details><summary>instrumentation-express: 0.31.1</summary>

### Bug Fixes

* **readme:** Correct urls to npm ([#1144](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1144)) ([d8767a9](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/d8767a9032dd7fb78b7fdd82f50c1f76e939d33e))
</details>

<details><summary>instrumentation-graphql: 0.31.0</summary>

### Features

* **graphql:** exported all graphql types ([#1097](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1097)) ([710103b](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/710103b4d9486fc2e5a9fa567ea1982f218ab4bf))
</details>

<details><summary>instrumentation-ioredis: 0.32.1</summary>

### Bug Fixes

* **ioredis:** requireParentSpan not applied to connect spans ([#1151](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1151)) ([d3cb60d](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/d3cb60d28e186b42f0c17ab48df8757555bbe6e0))
</details>

<details><summary>instrumentation-mysql: 0.31.1</summary>

### Bug Fixes

* **mysql:** set proper context for outgoing queries ([#1140](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1140)) ([59f7bce](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/59f7bce383a754bd5f08ae4e5a75e27de6d3d6e2))
</details>

<details><summary>instrumentation-net: 0.30.1</summary>

### Bug Fixes

* handle string ports for Socket.connect ([#1172](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1172)) ([aa6a0dd](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/aa6a0ddee67730b41630a56d94545ce91c586b14))
</details>

<details><summary>instrumentation-pg: 0.31.1</summary>

### Bug Fixes

* **pg:** avoid disjoint spans from pg instrumentation ([#1122](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1122)) ([82b8a84](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/82b8a8490628282efba334cb19f43bb6bf796548))
</details>

<details><summary>instrumentation-pino: 0.32.0</summary>

### Features

* improve pino instrumentation by patching additional exports of the same function ([#1108](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1108)) ([4e4d22e](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/4e4d22eee0e480188b4458b5a859d7cf4b7743d8))
</details>

<details><summary>instrumentation-redis-4: 0.33.0</summary>

### Features

* add redis 4 connect span ([#1125](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1125)) ([dbf37fb](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/dbf37fb99b9168ebd0febc0da0ec21c0082e9967))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by dyladan** [comment]
@open-telemetry/javascript-approvers I can't merge this until there is a ✅

**Review by legendecas — APPROVED** [review]

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.32.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-sdk-v0.9.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-express-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-graphql-v0.31.0 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-ioredis-v0.32.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-net-v0.30.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pg-v0.31.1 :sunflower:

**Comment by dyladan** [comment]
:robot: Release is at https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-pino-v0.32.0 :sunflower:

**Pull request merged**
