### PR TITLE
chore: add AWS resource detector ownership

### PR DESCRIPTION
**Pull request by willarmiros**
Extending #606

### CODE REVIEW

**Comment by dyladan** [comment]
@legendecas looks like you originally authored this package are you ok with ceding ownership to the AWS team?

**Comment by willarmiros** [comment]
I mistakenly thought one of our engineers had contributed this package! Happy to share ownership with @legendecas or figure out something else

**Comment by dyladan** [comment]
Please add a line like https://github.com/open-telemetry/opentelemetry-js-contrib/pull/607/files#diff-af95f165939b97358f23dede116533228d8f681e32bc67b5d806e7122db6a562R8

**Comment by willarmiros** [comment]
Done

**Review by Flarna — APPROVED** [review]

**Review by vmarchaud — APPROVED** [review]

**Review by legendecas — APPROVED** [review]
@dyladan @willarmiros LGTM with ownership changes! 

Actually, I was just moving the packages from opentelemtry-js repo in a very recent PR.

**Pull request merged**
