### PR TITLE
feat(koa): Use exported strings for attributes

### PR DESCRIPTION
**Pull request by MrFabio**
## Which problem is this PR solving?

* Updates [Update usage of semantic conventions to new exported strings #2025](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2025)

## Short description of the changes

In koa instrumentation package:
* Update `@opentelemetry/semantic-conventions` to `^1.22`
* Replace `SemanticAttributes.HTTP_ROUTE` with exported string `SEMATTRS_HTTP_ROUTE`

### CODE REVIEW

**Review by pichlermarc — DISMISSED** [review]

**Review by pichlermarc — COMMENTED** [review]
Oh, needs a `npm run lint:fix` before we can merge this.
(see failing lint step)

**Comment by maryliag** [comment]
have you ran `npm install` on the package? I'm not seeing the correspondent `package-lock.json` changes on
```
"@opentelemetry/instrumentation-koa": {
      "version": "file:plugins/node/opentelemetry-instrumentation-koa",
      "requires": {
        "@koa/router": "12.0.0",
        ...
        "@opentelemetry/semantic-conventions": "^1.0.0",  <--- this one should be the new version
```

**Review by maryliag — APPROVED** [review]

**Comment by MrFabio** [comment]
Thanks @maryliag !

**Comment by maryliag** [comment]
I just don't have permission to merge, so hopefully someone else can merge this for you 😄

**Review by pichlermarc — APPROVED** [review]

**Pull request merged**
