### PR TITLE
fix(plugin-document-load): check if getEntriesByType is available before using it

### PR DESCRIPTION
**Pull request by mhennoch**
## Which problem is this PR solving?

- When performance.getEntriesByType is undefined error is thrown(and fallback performance.timing is not used). This happens in Safari 10.1 for example where getEntriesByType is undefined but performance.timing is available.

## Short description of the changes

- Check if performance.getEntriesByType is present before using it.

### CODE REVIEW

**Review by obecny — APPROVED** [review]
lgtm, thx for contribution

**Comment by mhennoch** [comment]
Any idea when this will get merged?

**Comment by obecny** [comment]
@mhennoch we cannot merge until you sign the CLA

**Comment by mhennoch** [comment]
@obecny I signed it after it initially failed. Under checks it says: 
EasyCLA — EasyCLA check passed. You are authorized to contribute.

**Comment by obecny** [comment]
it was marked as not  signed, until you commented on PR then the CLA check is run again, now I see it is fine

**Pull request merged**
