### PR TITLE
fix: fix CI by forcing colors@1.4.0

### PR DESCRIPTION
**Pull request by Rauno56**
## Which problem is this PR solving?

`colors` a widely used terminal styling package is causing our CI to crash. Not sure when that will be fixed and how so meanwhile I'll add a dev dependency on colors@1.4.0 to force npm to install an older version.

### CODE REVIEW

**Review by legendecas — APPROVED** [review]
Can we use the npm [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)? Though it is only available on npm v8.3.0 and later.

**Review by dyladan — APPROVED** [review]
LGTM % the question about overrides

**Comment by Rauno56** [comment]
Yeah, it doesn't help us on node <16 :(

**Comment by Rauno56** [comment]
I'll merge this for now. It's definitely not a permanent solution.
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/826

**Pull request merged**
