### PR TITLE
chore: update lerna to v7 and migrate to npm workspace

### LINKED ISSUE #904: Local build differs from CI build
Bootstrapping differs between local builds using `npm install` in root folder and CI builds.

Local builds execute [`lerna bootstrap --no-ci`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/b9a13817b21f6be804479f24619c765b33ec0add/package.json#L25)

CI builds execute [`lerna bootstrap --no-ci --hoist --nohoist='zone.js' --nohoist='mocha' --nohoist='ts-mocha'`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/b9a13817b21f6be804479f24619c765b33ec0add/.github/workflows/unit-test.yml#L144)

I can't tell which variant is better/more correct but I think there should be no difference.

Refs.: #900 (fixes an issue which happens in CI but not local)

### LINKED ISSUE #1542: Update dependency lerna to `v7`
`The "bootstrap" command was removed by default in v7, and is no longer maintained.`, which means we'd have to change the way we link packages, possibly by using npm workspaces. 

Further information:

- [ ] #1541, we will have to also update the pinned version here to v7

See also:

Same issue in the otel-js core repo https://github.com/open-telemetry/opentelemetry-js/issues/3894

### PR DESCRIPTION
**Pull request by chigia001**
## Which problem is this PR solving?

- As lerna@7 drop support for `lerna bootstrap`, `lerna link`, and `lerna add`, we must depend on the package's manager native solution
Fixes #904 
Fixes #1542

## Short description of the changes

- Add "workspaces" definition to root package.json
- Remove the "prepare" script in each workspace's package.json
- Clean up `gts` as it does not use anymore; I just happened to see this because its part of the `lerna bootstrap` arguments
- Fix any hoist issue that occurred with the new setup:
  - `@types/sinon<10.0.14` depend on `@sinonjs/fake-timers` which install a very old version of sinon => this cause some compile issue
  - `zone.js` => instrumentation-user-interaction depends on zone.js's type, but the way the type is defined in zone.js is generated, it can't be used with the import statement. We must use `/// <reference` syntax so that we don't need to fix the path to `zone.js/dist/zone.js.d.ts`
- Update GH's action cache using setup-node
  - This will cache the ~/.npm instead of node_modules folder and won't cache any generated package-lock.json 
    - this previous setup might create a cache lock file that we unable to replicate on local machine
    - as we also don't use `yarn bootstrap` anymore, the previous [best practice for node lerna cache](https://github.com/actions/cache/blob/main/examples.md#node---lerna) not apply for this case
- Remove lerna:link in .tav.yml file

There might be some hoist issues in the future, and the current npmcli script doesn’t provide enough support for us for more complex hoisting like what `lerna` used to provide.

## Next Step

As lerna@7 is just provide some additional feature on top of nx, ee might consider to include nx.json to increase caching between task and apply for nx-cloud. Nx-cloud should be free for OSS project like opentelemetry-js-contrib. Those change might also fix issue with #1473

### CODE REVIEW

**Comment by chigia001** [comment]
the default node-14 env is bundle with npm@6's which seem not support npm workspace.
I'm looking into node-18's unit test issue.

**Comment by chigia001** [comment]
nx@16.5.0 are using nodejs's global performance object, which introduced in node@16. this cause nx fail on node@14
https://github.com/nrwl/nx/issues/17986

**Comment by chigia001** [comment]
I will need some more time to test for tav.

**Comment by DanielLoyAugmedix** [comment]
@chigia001 why did this get closed and not merged in?

**Comment by chigia001** [comment]
@DanielLoyAugmedix  I have a new pr for this but still WIP

**Pull request closed without merging**
