### PR TITLE
fix!(ioredis): net.peer.ip -> db.connection_string

### PR DESCRIPTION
**Pull request by trask**
This is split out of #913 because ioredis tests seem to hang CI.

### CODE REVIEW

**Comment by trask** [comment]
@open-telemetry/javascript-approvers is this by any chance a known issue that CI is hanging on `ioredis` tests?

**Comment by vmarchaud** [comment]
cc @Rauno56  since i think you worked a little bit on the ioredis tests ?

**Comment by dyladan** [comment]
> @open-telemetry/javascript-approvers is this by any chance a known issue that CI is hanging on `ioredis` tests?

Not that I'm aware of

**Comment by trask** [comment]
what do you know, when I fixed the code, it fixed CI 😭 sorry for the noise

**Comment by dyladan** [comment]
> what do you know, when I fixed the code, it fixed CI 😭 sorry for the noise

😮

**Review by dyladan — APPROVED** [review]

**Review by Flarna — APPROVED** [review]

**Comment by blumamir** [comment]
@dyladan - the name of the PR starts with `fix!`, how will release please handle that?
looks like it does not generate a release for the package

**Comment by dyladan** [comment]
According to this it should have treated it as breaking https://github.com/googleapis/release-please#how-should-i-write-my-commits

**Pull request merged**
